function BioGustavo() {
    return (
        <>
            <h2>Bio</h2>
            <h3>Contenido</h3>
            <table className="table">
            <tbody>
                <tr>
                    <th className="lead"><a href="#soda"><b>Soda Stereo</b> | </a></th>
                </tr>
                <tr>
                    <td><a href="#conquista">Soda Stereo: <em>La conquista de Latinoamérica</em> | </a></td>
                </tr>
                <tr>
                    <td><a href="#final">Soda Stereo: <em>El final</em> | </a></td>
                </tr>
                <tr>
                    <th className="lead"><a href="#solista"><b>Etapa solista</b> | </a></th>
                </tr>
                <tr>
                    <td><a href="#bocanada">Etapa solista: <em>Bocanada</em> | </a></td>
                </tr>
                <tr>
                    <td><a href="#seh">Etapa solista: <em>Siempre es hoy</em> | </a></td>
                </tr>
                <tr>
                    <td><a href="#ahivamos">Etapa solista: <em>Ahí vamos</em> | </a></td>
                </tr>
                <tr>
                    <td><a href="#fn">Etapa solista: <em>Fuerza natural</em> | </a></td>
                </tr>
                </tbody>
            </table>
            <br />
            <h4 id="soda">Soda Stereo </h4>
            <p><strong>Gustavo Cerati</strong> nació  el 11 de agosto de 1959 en Capital Federal, Buenos Aires, Argentina. Su carrera  musical comienza en el año 1983, aunque antes de eso, ya a los nueve años  estudiaba guitarra, a los doce conformó un trío con el cual se presentaba en  fiestas particulares, participaba de todos los eventos que se realizaban en el  colegio religioso al que concurría, y llegó a dirigir el coro de la iglesia.</p>
            <p>Sus  primeras influencias musicales fueron grupos como King Crimson y  especialmente The Beatles. También David  Bowie, Pink Floyd y guitarristas como Jimmy Page (<em>Led Zeppelin</em>) y Ritchie  Blackmore (<em>Deep Purple</em>)</p>
            <p>En el año 1979 en la Universidad de El Salvador cursando  la carrera de Publicidad, <strong>Gustavo Cerati</strong> conoce a <strong>Héctor &quot;<em>Zeta</em>&quot; Bosio</strong> (<em>futuro  bajista del grupo <strong>Soda Stereo</strong></em>), junto a otro grupo de estudiantes con los cuales  intercambiaban discos de <strong>The Police,  XTC, Elvis Costello</strong>. Mientras estudiaba tocó en dos bandas: una de rock and  roll y blues, y otra de fusión. <br />
                A partir del año 1982 los dos músicos comienzan a  proyectar la formación de una banda en la que tocarían temas propios. En ese  momento conocen a<strong> Charly Alberti</strong>, y  de ahí en más, luego de un período donde prueban distintas formaciones (<em>incluyendo por momentos a músicos como Richard Coleman, Daniel Melero y  Andrés Calamaro entre otros</em>) y distintos nombres, se constituye formalmente <strong>Soda Stereo</strong>. <br />
                <br />
                La banda estableció la formación de trío:</p>
            <ul>
                <li> Gustavo Cerati: voz y guitarra</li>
                <li> Zeta Bosio:  bajo</li>
                <li>Charly Alberti:  batería</li>
            </ul>
            <p>Desde el  comienzo el grupo se ocupó de construir su propia imagen; ayudados por Alfredo  Lois (<em>compañero de la universidad</em>) cuidaron los detalles estéticos, el  maquillaje, los peinados, y - <em>más adelante</em>- la tapa de los primeros discos y  la puesta en escena de los recitales. Los primeros shows fueron en Julio del  año 1983 en la discoteca Airport y en el Stud Free Pub. Desde ese momento  recorrieron el circuito de pubs, con escala obligada en el Café Einstein y  Zero, que por entonces representaban el centro de la movida underground del  momento donde tocaban bandas como Sumo y Los Twist. </p>
            <p><strong>Soda Stereo</strong> firmó contrato con la compañía discográfica Sony Music en  Agosto de ese año; y en el 1984 comenzaron la grabación de su primer LP <strong>&quot;<em>Soda Stereo</em>&quot; (1984)</strong>. El disco contó  con la producción artística de Federico Moura (<em>líder de otro legendario grupo:  &quot;<strong>Virus</strong>&quot;</em>), y fue presentado en el mes de diciembre en el Teatro Astros de  la Capital Federal.</p>
            <p>Su  segunda producción, <strong>&quot;<em>Nada Personal</em>&quot; (1985), </strong> fue editada en octubre del 85, y presentada  oficialmente en el Estadio de Obras Sanitarias ante 16.000 personas en cuatro  funciones. A partir de esos conciertos, las ventas del disco comenzaron a  crecer aceleradamente, pasando del disco de oro que habían conseguido durante  el verano hasta el platino, y llegando a doblar esa cifra en los meses  siguientes. <br />
                Simultáneamente el trío grabó el video del tema <strong><em>&quot;Cuando  pase el temblor&quot; </em></strong>bajo la dirección de Alfredo Lois en las ruinas del  Pucará de Tilcara, que junto a la filmación de la presentación en el estadio  Obras fue editado en formato video home. Este clip fue nominado como Video  finalista del 12° World Festival of Video and TV en Acapulco unos años después.</p>
            <p>1985 fue  el año de la consagración de <strong>Soda Stereo</strong> ante el público  argentino; y ya en 1986 comenzaría con muchísimo éxito su carrera en el  exterior. </p>
            <h5 id="conquista">La conquista de Latinoamérica </h5>
            <p>El  tercer disco <strong>&quot;<em>Signos</em>&quot; (1986)</strong>, tuvo la participación del tecladista Fabián  Von Quintiero, el guitarrista Richard Coleman y Celsa Mel Gowland en coros. Una vez terminada la grabación del  mismo, <strong>Soda Stereo</strong> inició una gira con presentaciones en vivo en las  ciudades más importantes de Latinoamérica. Para esta época, el público que  seguía a la banda había aumentado considerablemente y se apropiaron de sus canciones,  como &quot;<em>Persiana americana</em>&quot; y &quot;<em>Signos</em>&quot;. En Chile, la prensa llegó a  definir el fenómeno de la banda como <strong>&quot;<em>Sodamanía</em>&quot;.<br />
            </strong>Al finalizar el año, la banda había logrado abrir las puertas del mercado  latinoamericano a la música nacional.<br />
                La  presentación oficial del disco se realizó en Argentina en el Estadio Obras, y  fue seguida por una larga gira realizada por el interior del país. El álbum se convertió en disco de platino en Argentina y doble platino en  Chile.<br />
                En 1987  el grupo realizó un tour por  Perú, Bolivia, Ecuador, Colombia,  Venezuela, Costa Rica y México; realizando 22 conciertos en 17 ciudades  frente a casi 150.000 personas. Con el material grabado en los distintos puntos  del viaje se realizó el disco en vivo  <em>&quot;<strong>Ruido Blanco</strong>&quot; (1987)</em>,  que fue mezclado en la Isla de Barbados.</p>
            <p>A partir  de 1988, los músicos comenzaron a trabajar en el nuevo disco, cuya producción  artística estuvo a cargo de Carlos Alomar, quien acredita trabajos con David  Bowie, Mick Jagger, Iggy Pop y Paul Mc Cartney entre otros.<br />
                Luego de ser  grabado en un estudio de Nueva York, <em>&quot;<strong>Doble Vida</strong>&quot; (1988)</em> fue presentado  en una discoteca de esa ciudad y en algunos puntos de México y Colombia. Hits  como <em>&quot;Lo que sangra (la cúpula)</em>&quot;, &quot;<em>Corazón Delator</em>&quot;, y &quot;<em>En la ciudad de la Furia</em>&quot; afianzaron  definitivamente a la banda dentro de las preferencias del público local. El  video de este último tema fue finalista del MTV Music Awards en la categoría de  &quot;<em>Mejor video Extranjero</em>&quot;, en una época donde <strong>MTV Latinoamérica no había nacido aún</strong>. <br />
                El 3 de  diciembre, el disco fue presentado oficialmente en Buenos Aires ante 25.000 personas que  asistieron al estadio de Obras Sanitarias y la euforia se repitió el 27 del  mismo mes en un concierto multitudinario (<em>150.000 personas</em>) en el Festival Tres  Días por la Democracia.<br />
                Con la  cifra de un millón de discos vendidos,  <strong>Soda</strong> inició  una gira nacional de presentación del disco que comprendió 30 shows en casi  todo el país ante 270.000 espectadores durante los primeros días de 1989, que  fue seguida por una gira latinoamericana y la realización de dos conciertos en  Los Angeles. </p>
            <p>A fines de 1989 grabaron una nueva versión de <em>&quot;Languis&quot;</em> (<em>canción incluída en <strong>&quot;Doble Vida&quot;</strong></em>) y un tema nuevo llamado &quot;<em>Mundo de Quimeras</em>&quot;, los que fueron editados en el  maxi-simple <em>&quot;<strong>Languis</strong>&quot; (1989)</em> junto a versiones remixadas de &quot;<em>En el borde</em>&quot; y &quot;<em>Lo que sangra (la cúpula)</em>&quot;. Luego de editado el disco, realizan la primera presentación de una banda de rock en español en territorio estadounidense con un show <em>sold out</em> en The Palace de Los Angeles. </p>
            <p>A principios de 1990, la banda se presenta por primera vez en Argentina en un estadio de fútbol (<em>estadio Vélez Sarsfield</em>), en la cual compartieron cartel en igualdad de condiciones junto al dúo inglés Tears For Fears, en un show ante 32.000 personas.</p>
            <p>A  mediados de 1990, <strong>Soda Stereo</strong> vuelve a grabar un disco  de estudio con el aporte conceptual de Daniel Melero, y la participación de  Andrea Alvarez y Tweety González - <em>todos importantes músicos de la escena  rockera nacional</em> - en calidad de invitados.<br />
                <em>&quot;<strong>Canción  Animal</strong>&quot; (1990)</em> significó para la banda el  acceso al mercado español plasmado en el futuro a través de la realización de  shows en las ciudades de Sevilla, Madrid, Barcelona, y Valencia en el año 92, y  una maratónica y nunca repetida por ningún artista &quot;<em><strong>Gira Animal</strong></em>&quot; que abarcó  treinta ciudades de Argentina, incluyendo lugares donde nunca se había presentado una banda de la envergadura de Soda Stereo. Y en cada lugar, se respetó la misma infraestructura de show, que para ese momento era inédita para un artista local. <br />
                El punto más alto de la gira fue el recital en el estadio de Vélez Sarsfield, a fines de Diciembre ante 40.000 personas. <br />
                A comienzos de 1991 se presentan en un gran  concierto gratuito en la ciudad de Punta del Este (<em>Uruguay</em>), y hacia mitad de año, baten un nuevo record realizando 14  presentaciones en el Teatro Gran Rex de la Ciudad de Buenos Aires. <br />
                De estos shows surgió el EP <em>&quot;<strong>Rex Mix</strong>&quot; (1991)</em> el cual incluía versiones en vivo grabadas esas noches y también versiones remixadas junto al tema nuevo &quot;<em>No necesito verte (para saberlo)&quot;</em>.
                La banda cerraría ese año con un nuevo record. Un nuevo concierto gratuito y  masivo que fue presenciado por 250.000 personas en plena  Avenida 9 de Julio de la Ciudad de Buenos Aires.</p>
            <p>A comienzos de   1992 - <em>y paralelamente a las actividades de la banda</em> - <strong>Gustavo  Cerati</strong> editó un disco en conjunto con el músico Daniel Melero, quien había  participado anteriormente con la banda como colaborador artístico y formaba parte de los músicos invitados en las presentaciones en vivo durante la gira de &quot;<em>Canción Animal&quot;</em>.</p>
            <p><em>&quot;<strong><a href="http://cerati.com/proyectos/colores_santos/">Colores  Santos</a></strong>&quot; (1992)</em> - <em>que también contó con el aporte de  los músicos Flavio Etcheto y Carola Bony</em> -   fue grabado en el estudio Supersónico de los <strong>Soda</strong>, y no fue presentado  en vivo.</p>
            <p>La  grabación del siguiente disco de <strong>Soda Stereo</strong> también se realizó en el  estudio Supersónico durante 1992. <strong><em>&quot;Dynamo&quot;</em></strong> <em>(1992)</em> fue editado en el  mes de Septiembre y fue presentado con 6 shows en el Estadio Obras a fines de ese mismo  año. La banda quiso que cada show contara con una banda nueva como invitados y así estuvieron de soporte bandas como Babasónicos, Juana La Loca,  Martes Menta y Tía Newton, las cuales protagonizaban el nuevo escenario musical  de Buenos Aires. </p>
            <p> En enero de 1993 emprendieron su sexto tour latinoamericano,  visitando México, Chile, Paraguay, y Venezuela.<br />
                Una vez  finalizada la gira presentación de <strong><em>&quot;Dynamo&quot;</em></strong>, se <strong></strong>toman un largo  descanso que hicieron crecer los rumores de separación de la banda. <br />
                A finales de año se edita <em>&quot;<strong>Zona de Promesas</strong>&quot; (1993)</em>, un compilado de remixes de clásicos temas  de la banda, y la inclusión de una canción inédita que daría título al álbum.<br />
                Tres años  después el grupo editará lo que sería su último disco en estudio.</p>
            <p>Varias  cosas sucedieron durante ese tiempo. Algunas de ellas fueron el cambio de  compañía discográfica por parte de la banda (<em>de Sony a BMG</em>); la edición del  disco <em>&quot;<strong>Amor Amarillo</strong>&quot; (1993)</em>: primer trabajo en solitario del líder  de <strong>Soda</strong>,  que coincidió con el nacimiento del primer hijo de Gustavo, y fue grabado en  Chile y Buenos Aires con la participación de Zeta Bosio.<br />
                El año  95 marcó el regreso del grupo con la edición de <em>&quot;<strong>Sueño Stereo</strong>&quot; (1995)</em>.  Temas como &quot;<em>Paseando por Roma</em>&quot;, &quot;<em>Zoom</em>&quot;, y el primer corte de difusión &quot;<em>Ella usó mi cabeza como un revólver</em>&quot;, se escucharon en las  radios y motivaron el regreso de la banda a los escenarios porteños. Nuevamente  el Gran Rex fue el teatro elegido para presentar el disco; emprendiendo durante  ese año  una nueva gira latinoamericana  y la realización de un recital gratuito para  el festejo del 113° aniversario de la ciudad de La Plata (<em>Capital de la provincia Buenos  Aires</em>) ante 200.000 personas.</p>
            <p>En 1996 <strong>Soda</strong> realizó un tour por Estados Unidos (<em>Los Angeles, Chicago, Nueva York, y Miami</em>) para  presentar su última producción, cosechando elogiosas críticas de los medios  norteamericanos más importantes. A mediados de año grabaron en Miami un  concierto para la cadena de música MTV. Este show tuvo la particularidad de que la banda no respetara la  consigna original sobre el uso de instrumentos desenchufados. <em>&quot;<strong>Comfort  y Música para Volar</strong>&quot; (1996)</em> – <em>disco que registra  esta presentación</em> – es una versión <em>plugged</em> de 11 temas de la banda y que incluye además 4 temas nuevos que habían quedado fuera de &quot;Sueño Stereo&quot; y un track interactivo con historietas e imágenes en video de la presentación en MTV. <br />
                Este disco constituye la última producción  discográfica realizada como banda.<br />
            </p><br />
            <h5 id="final">El final de Soda Stereo </h5>
            <p> A partir  de ese momento, <strong>Soda</strong> entró en un silencio que sólo se vió interrumpido  por las versiones no oficiales de su separación definitiva.</p>
            <p>Mientras  tanto <strong>Gustavo</strong> se unió a tres  músicos chilenos no profesionales (Andrés Bucci, Guillermo Ugarte, y Christian  Powditch), constituyendo <strong><a href="http://cerati.com/proyectos/plan_v/">Plan V</a></strong>,  proyecto electrónico que se plasma en dos discos: <em>&quot;<strong>Plan V</strong>&quot; (1996)</em>, de  origen trasandino; y el segundo trabajo <em>&quot;<strong>Plan Black V Dog</strong>&quot; (1998)</em>,  que fue compartido con los ingleses Black  Dog, y editado en el año 1998 luego de la separación de <strong>Soda Stereo</strong>.  </p>
            <p><strong>El 1° de Mayo    de 1997, la banda anunció oficialmente su separación mediante un comunicado de prensa</strong>. Al día siguiente, todos los diarios se hacen eco de la noticia y el diario <a href="http://clarin.com">Clarín</a> dedica un gran espacio en su portada para ello. Gustavo publica luego en el suplemento &quot;<em>Sí</em>&quot; (<em>suplemento joven del diario Clarín</em>) lo que sería &quot;<em>La carta del adiós</em>&quot; .<br />
            </p>
            <blockquote lang="es" title="Carta de Gustavo Cerati sobre el final de Soda Stereo">&quot;Estas líneas surgen de lo que he percibido estos días en la  calle, en los fans que se me acercan, en la gente que me rodea, y en mi propia  experiencia personal. Comparto la tristeza que genera en muchos la noticia de  nuestra separación. Yo mismo estoy sumergido en ese estado porque pocas cosas  han sido tan importantes en mi vida como Soda Stereo. Cualquiera sabe que es  imposible llevar una banda sin cierto nivel de conflicto. Es un frágil  equilibrio en la pugna de ideas que muy pocos consiguen mantener por quince  años, como nosotros orgullosamente hicimos. Pero, últimamente, diferentes  desentendimientos personales y musicales comenzaron a comprometer ese  equilibrio. Ahí mismo se generan excusas para no enfrentarnos, excusas  finalmente para un futuro grupal en que ya no creíamos como lo hacíamos en el  pasado. Cortar por lo sano es, valga la redundancia, hacer valer nuestra salud mental  por sobre todo y tambin el respeto hacia todos nuestros fans que nos siguieron  por tanto tiempo. Me gustara aclarar que este estado no tiene nada que ver con  mis frecuentes salidas a Chile ni con los esporádicos proyectos musicales que  haya realizado al margen de Soda. <br />
                Un fuerte abrazo".</blockquote>
            <p>Durante los  meses de Agosto y Septiembre de ese año llevaron a cabo una gira  latinoamericana por México, Venezuela, y Chile; culminando su trayectoria con  una despedida oficial realizada en Buenos Aires el 20 de septiembre en el  Estadio de River Plate ante más de  70.000 personas. <br />
                El registro de este show fue plasmado en dos discos editados a  fin de ese año llamados <strong><em>&quot;El Último Concierto A y B&quot;</em></strong> (<em>1997</em>).<br />
            </p><br />
            <h4 id="solista">Etapa solista </h4>
            <p>Luego de  la separación del grupo, <strong>Gustavo  </strong>tuvo  un tiempo de actividad en solitario que alternó entre la composición de un  nuevo álbum de canciones; la experimentación en el campo de la electrónica; y  la participación en  el disco homenaje  latino a The Police - <em>&quot;<strong>Outlandos D´Americas</strong>&quot; (1998)</em> - interpretando una versión de su autoría del tema <strong>&quot;<em>Bring on the</em></strong> <em><strong>Night</strong></em>&quot; junto a <a href="http://www.andysummers.com/">Andy Summers</a> (<em>miembro original de The Police</em>) y el reconocido baterista <a href="http://www.vinniecolaiuta.com/">Vinnie Colaiuta</a>. <br />
                Antes de  la edición de su primer trabajo solista, compuso un material electrónico a  dúo con el músico Flavio Etcheto. Con el nombre de <strong><a href="http://cerati.com/proyectos/ocio/">Ocio</a></strong>, editaron el disco <strong><em>&quot;Medida  Universal&quot;</em></strong> a mediados de 1999.<br />
            </p><br />
            <h5 id="bocanada">Bocanada</h5>
            <p> El 28 de Junio  de ese mismo año, le da vida  a uno de los discos más esperados desde la separación de Soda Stereo, <em>&quot;<strong><a href="http://cerati.com/bocanada/">Bocanada</a></strong>&quot;  (1999)</em>, con el que dió comienzo oficialmente a su carrera solista.<br />
                Grabado  en el estudio CasaSubmarina y en  Abbey Road de Londres, el álbum  salió a la venta en el mercado argentino siendo disco de oro. El mismo contó  con la participación de los músicos <strong>Flavio  Etcheto</strong> en teclados, <strong>Leo García</strong> en coros y voz, <strong>Fernando Nalé</strong> en  bajo, y <strong>Martín Carrizo</strong> en batería  (<em>quienes también formarían parte de la banda en la gira de presentación de ese disco</em>);  además de los arreglos en cuerdas de <strong>Alejandro  Terán</strong> y la inclusión particular de una orquesta de 48 músicos convocada  especialmente para la grabación del tema &quot;<em>Verbo Carne</em>&quot;.</p>
            <p><strong><em>&quot;Bocanada&quot; </em></strong>cosechó elogiosas críticas entre la prensa y el  público tanto a nivel nacional como internacional; con igual repercusión en los  shows realizados durante la gira que comprendió Argentina, México, Chile, El Salvador, Panamá, Costa Rica, Ecuador, Colombia, Estados Unidos, España y Venezuela; tocando inclusive en algunos  países a los que el músico nunca antes había visitado.<br />
                En  Argentina, la presentación oficial del mismo se realizó en el Teatro Gran Rex  durante seis funciones a sala llena y con conciertos llevados a cabo también  en el interior del país. Luego en 2000, repetiría la presentación en Buenos Aires, pero esta vez con dos funciones en el estadio Obras. <br />
                Finalizando  1999, <strong>Gustavo </strong>obtiene el  reconocimiento de la mayoría de los medios especializados de Argentina, que  manifestaron su opinión en los resultados de las encuestas que repasaron la  producción musical de ese año,   consagrándolo en distintos rubros tales como &quot;<em>Mejor Disco</em>&quot; y &quot;<em>Mejor  Solista</em>&quot; del año; así como también premiaron su trayectoria eligiéndolo  &quot;<em>Artista de la Década</em>&quot; junto al popular músico argentino: <strong>Charly García</strong>.</p>
            <p>Los  siguientes dos años lo tuvieron ocupado en distintas realizaciones, mientras  iba generando e ideando nuevos temas para un próximo álbum. En el año 2001 se edita  la banda de sonido del film &quot;<em><strong>+  Bien</strong>&quot;</em>, una<strong></strong> producción independiente de <strong>Eduardo Capilla</strong>,  director de videos y realizador audiovisual. El disco fue nominado como &quot;<em>Mejor Album Instrumental Pop</em>&quot; para los Grammy  Latinos. En esta oportunidad GUstavo Cerati es convocado por primera vez para la actuación. Protagoniza la trama junto a la conductora de MTV, <strong>Ruth Infarinato</strong>. </p>
            <p>En Agosto de 2001, se realiza  <a href="http://cerati.com/eventos/#episodios">un concierto a  puertas cerradas en el Teatro Avenida</a>, con una orquesta de 42 músicos  especialmente armada por el arreglador y director <strong>Alejandro Terán</strong> y se realiza la grabación de lo que luego sería  el  disco <strong>&quot;<em>11 Episodios Sinfónicos</em>&quot;</strong><em> (2001)</em><strong>, </strong>que  registra versiones orquestadas sobre clásicos de toda su carrera. <br />
                <strong><a href="http://cerati.com/varios/11_episodios_sinfonicos/">11 Episodios sinfónicos</a>, </strong>con producción de<strong> Diego  Sáenz, </strong>desembarca luego en el Teatro Colón de la ciudad de  Buenos Aires con dirección de Alejandro Terán, ofreciendo al público un  concierto verdaderamente atípico y conmovedor, con una excelente repercusión de  la prensa nacional. La Orquesta Sinfónica Nacional, dirigida por Pedro  Ignacio Calderón, llevó a cabo la primera parte instrumental de la velada.<br />
                El show fue también presentado en vivo en México, donde el álbum se mantuvo largamente en los  primeros puestos en el ranking de ventas. Se colmó el Auditorio  Nacional del Distrito Federal para ver a <strong>Cerati</strong> junto a una orquesta de cuarenta músicos locales. Luego la serie de presentaciones continúa en el Teatro  Teresa Carreño de Caracas, Venezuela, en el Estadio  San Carlos de Apoquindo de Santiago, Chile y en tres shows en el Teatro Gran  Rex de Mendoza, Argentina, siempre con orquestas locales de más de 65 músicos  en escena. <br />
            </p><br />
            <h5 id="seh">Siempre es hoy </h5>
            <p>A fines de Noviembre de 2002 sale a la venta <strong>&quot;<em><a href="http://cerati.com/siempre_es_hoy/">Siempre  es Hoy</a></em>&quot;, </strong>su tercer disco solista de estudio.<br />
                El técnico <strong>Sacha Triujeque</strong> y el músico y productor <strong>Toy Hernández </strong>(<em>Control Machete</em>) vinieron de México para realizar la  co-producción de la mezcla del disco. <br />
                Muestra influencias que se mezclaron con el pop, el hip hop y  el rock y se realiza una edición simultánea en  Argentina, Estados Unidos, México y Chile.<br />
                El disco fue presentado en la ciudad de Buenos Aires en el  Estadio Luna Park en Marzo de 2003 y luego en Septiembre en 3 funciones en el Teatro Gran  Rex.   <br />
                En este caso Gustavo armó una banda formada por los músicos: <strong>Flavius  Etcheto</strong> (<em>samplers</em>), <strong>Fernando Nalé</strong> (<em>bajo</em>), <strong>Leandro Fresco</strong> (<em>teclados y coros</em>), <strong>Pedro Moscuzza</strong> (<em>batería</em>) y <strong>DJ Zucker </strong>(<em>scratches  y loops</em>). En los coros, durante algunos shows participaron también <strong>Loló</strong> y <strong>Déborah de Corral </strong>y en el rap de &quot;<em>Altar</em>&quot;, <strong>Tea-Time</strong> (<em>Los Tetas</em>). <br />
                También participaron importantes músicos invitados como <strong>Charly García</strong> y  <strong>Domingo Cura.</strong><br />
                La gira de <strong><em>Siempre es Hoy</em></strong> comenzó a  fines de 2002 en Quito (<em>Ecuador</em>) y Cali (<em>Colombia</em>) y en 2003 recorre nueve ciudades de México, varias ciudades de Argentina, Perú, Chile, Venezuela,  Uruguay, San José de Costa Rica, Panamá, Puerto Rico y Estados Unidos (<em>Los  Angeles, Anaheim, Chicago y Nueva York</em>).</p>
            <p>En 2003 se edita <strong><em>&quot;<a href="http://cerati.com/siempre_es_hoy/#reversiones">Siempre  es Hoy: Reversiones</a>&quot;</em></strong> el cual propone  versiones remixadas por distintos artistas sobre los temas del disco &quot;<em>Siempre  es Hoy&quot;. </em>Se incluyen versiones de los ganadores del concurso de  remixes que se realizó por medio de <a href="http://cerati.com">su sitio web</a> y una selección de versiones  realizadas por artistas de Argentina,  México, Chile y Alemania. La forma en  que se realizó el concurso es inédita ya que los usuarios dispusieron de todas  las pistas del tema por separado. Se recibieron 350 temas de los que se  eligieron dos.<br />
                El disco tiene formato de disco doble y también fue editado un <a href="http://cerati.com/siempre_es_hoy/#vinilo"> vinilo</a> con 4 de los  temas seleccionados. </p>
            <p>En 2003  se edita además su primer <strong>DVD</strong>, el cual contiene el concierto completo de &quot;<strong><em>11  Episodios Sinfónicos&quot;</em></strong> grabado en el Teato Avenida de la ciudad de Buenos Aires. </p>
            <p>Paralelamente a la gira de presentación de &quot;<em>Siempre es Hoy</em>&quot;, Gustavo, Flavio Etcheto y Leandro Fresco, conforman el proyecto &quot;<em><a href="http://cerati.com/proyectos/roken/"><strong>Roken</strong></a></em>&quot;, un trío de laptos con el que se presentan en varios países, incluyendo el importante Festival BUE en Buenos Aires. <br />
                (<em><a href="http://cerati.com/proyectos/roken/">+ info</a></em>) <br />
                <br />
                <strong><em>&quot;<a href="http://cerati.com/varios/canciones_elegidas/">Canciones elegidas 93-04</a>&quot;</em></strong> es el siguiente paso en la  carrera musical de <strong>Gustavo</strong>. El disco recopila canciones de su carrera  solista e incluye un DVD con todos los videoclips solistas realizados hasta el momento. Además, contó con el tema inédito <em>&quot;Tu locura&quot;</em>, que fue tema original del programa de TV &quot;<em>Locas de amor</em>&quot; y por el que obtendría en 2005 una nominación a los Martín Fierro. El álbum tuvo una doble edición: una en España y otra en Argentina y fue  promocionado con una gira corta que abarcó los meses de Octubre a Diciembre de  ese año y llevó a <strong>Gustavo</strong> por Argentina, México, Chile y España. <br />
            </p>
            <br />
            <h5 id="ahivamos">¡Ahí vamos!</h5>
            <p> Hacia fines  de 2005 comienza a dedicarse enteramente a su nueva producción: &quot;<strong><em><a href="http://cerati.com/ahi_vamos/">Ahí vamos</a>&quot;</em></strong>, que se edita  simultáneamente en Argentina y México el 4 de abril de 2006. El  disco alcanzó el galardón de platino antes de su salida a la venta, al recibir pedidos por anticipado por más de 40,000  unidades en Argentina. Fue además excelentemente recibido tanto por la crítica como por el público. <br />
                Coproducido  por <strong>Gustavo </strong>y <strong>Tweety González</strong>, &quot;<em>Ahí vamos</em>&quot; representa una vuelta a sus raíces, con  una concepción y estructura sonora que parte de la guitarra.<br />
                La grabación de &quot;<strong><em>Ahí vamos&quot;</em></strong> cuenta con la  participación de grandes músicos que lo acompañaron ya en otras etapas de su  trayectoria musical: <strong>Richard  Coleman, Fernando Nalé, Leandro Fresco, Tweety González, Emmanuel Cauvet,  Fernando Samalea, Pedro Moscuzza, Bolsa Gonzalez, Flavius Etcheto, Capri; y  Loló  Gasparini y Paula Zotalis en coros.</strong><strong> </strong><br />
                En la mezcla, se sumó el ingeniero <strong>Héctor Castillo</strong>, quien ha trabajado con artistas de la talla de Pete Townshend, David Bowie, Lou Reed y  Suzanne Vega entre otros.<br />
                El disco  fue masterizado por <strong>Howie  Weinberg</strong> en el estudio &quot;<em>Masterdisk</em>&quot; de Nueva York. <br />
                La gira <strong><em>&quot;Ahí Vamos&quot;</em></strong> comienza en México  el 1° de Junio y continúa en Argentina para hacer cinco funciones en el legendario Estadio Obras (<em>rebautizado por esos días Estadio Pepsi Music</em>) entre el 16, 17, 18, 30 de Junio y 1° de Julio, junto a algunas ciudades  del interior del país. Luego sigue por Estados Unidos del 1° al 20 de Agosto y en Septiembre  seguirá recorriendo Latinoamérica. Del 29 de Agosto al 10 de Octubre  la gira se extiende por España y  el 12 de Octubre llega por primera vez en  su carrera a tocar en la ciudad de Londres, Inglaterra.<br />
                <br />
                Desde junio de 2006 a junio de 2007 la gira  “<em>Ahí vamos</em>” acumula más de 70 shows, en su mayor parte <em>sold-out, </em>por  Chile, Colombia, Costa Rica, España, Estados Unidos, Inglaterra, México, Panamá,  Perú, Puerto Rico, Santo Domingo,  Uruguay  , Venezuela además de Argentina. <br />
                La banda que acompaña a Cerati en  vivo está formada por: Richard Coleman, Fernando Nalé, Leandro Fresco y Fernando  Samalea. <br />
                Y son muchos los logros obtenidos  durante este período: <strong>ocho  nominaciones</strong> (<em>Mejor álbum artista de rock, Mejor videoclip -  Crimen -, Ingeniería de grabación, Interpretación - Crimen -, Producción,  Diseño de portada, Canción del año - Crimen - y Álbum del año</em>) para la <strong>9º Edición de los premios Gardel a la  música argentina,</strong> de las cuales ganó 7. Tal cantidad de nominaciones  establece un record ya que ningún álbum lo había logrado antes. <br />
                En su  presentación en <strong>Viña del Mar</strong>, Chile,   en febrero de 2007, el público conocido  por su exigencia, le otorgó a Cerati: <strong>Antorcha  de Plata, Antorcha de Oro y Gaviota de Plata </strong>convirtiéndose en uno de los  principales ganadores.<br />
                Además,  fue consagrado como el artista argentino más nominado a los Grammy y MTV  Latinos, ganando tres <strong>Grammys</strong> en las  categorías <strong>Mejor Álbum de Rock Vocal y  Mejor Canción de Rock</strong>, además del Grammy como productor del disco de  Shakira y <strong>un premio MTV como Mejor  Artista Sur</strong>.<br />
                En las  encuestas anuales de 2006 (<em>Clarín Página/12 Rolling Stone</em>) Gustavo Cerati y Ahí  vamos se ubicaron entre los favoritos de la prensa, sus pares músicos y el  público que lo votaron en categorías como: Disco, Tema - Crimen - , Video -  Crimen - , Tapa, Show - Junio, Estadio Pepsi Music -, Artista y Cantante entre  otras.</p>
            <p>Incluso,  Gustavo Cerati  fue <strong>reconocido por el Jefe de Gobierno  de la Ciudad de Buenos Aires como &quot;Personalidad destacada de la Cultura&quot;</strong>.<br />
                El  show cumbre de la gira, y seguramente de su historia solista, fue sin dudas el  <strong>multitudinario concierto que dió ante casi 200 mil personas el 10 de marzo de  2007</strong>, en Avenida Figueroa Alcorta y Pampa como cierre del ciclo de conciertos  gratuitos Verano 07 Vivi Buenos Aires, en el que además<strong> tuvo el placer de tocar junto a uno de  sus ídolos como lo es Luis Alberto Spinetta</strong>.<br />
                Ahí  Vamos fue editado en toda Latinoamérica, España y Estados Unidos, obteniendo <strong>Disco de Platino en Argentina</strong> y <strong>Disco de Oro en Chile</strong>.</p>
            <p>En Junio de 2007 Gustavo invita  al público a ser director del videoclip de <strong>“Lago  en el cielo”</strong>, el cuarto corte de difusión de su disco <em>“Ahí vamos</em>”.<br />
                Más de  5000 visitas diarias al site y 400 videos recibidos de todo el mundo (<em>Alemania,  Colombia, Costa Rica, Chile, España, Inglaterra, México, Perú, República  Dominicana, además de Argentina</em>), fueron el resultado de la convocatoria. El  director <strong>Andrés Fogwill </strong>se encargó  de seleccionar los fragmentos de cada video ganador y compaginarlos para componer  el resultado final. Además, filmó el principio y el final del video.</p>
            <p>El  sábado 7 de julio de 2007, Cerati participó en Hamburgo del <strong>Festival Live Earth</strong> como invitado de <strong>Shakira</strong>, el único músico argentino que  intervino en dicho evento.</p>
            <p>Entre  julio y diciembre de 2007, Gustavo Cerati estuvo abocado a la Gira <strong>“Me verás volver”</strong> con <strong>Soda  Stereo</strong>, en un regreso histórico que los llevó a realizar 22 conciertos en  nueve países: Argentina, Chile, Ecuador, México, Estados Unidos, Colombia,  Panamá, Venezuela y Perú.</p>
            <p>Casi 1  millón de personas estuvieron presentes en la gira “<em>Me verás volver</em>”, en la cual  superaron records de venta en varias ciudades.</p>
            <p>En 2008, <strong>“<em>Ahí vamos</em>”</strong> vuelve a estar nominado  para los <strong>Premios Gardel</strong>, en esta  oportunidad en la categoría Mejor DVD.<br />
                El DVD,  realizado por <strong>Diego Sáenz</strong>, fue  registrado en los recitales presentación de Ahí Vamos entre junio y julio de  2006 en Buenos Aires. Entre los extras figuran fotos y un documental sobre la grabación del álbum y otro sobre la gira (<em>40  minutos de imágenes de backstage y de los viajes de la gira que abarcó más de  60 shows sold-out por España, estados Unidos, México, Londres, Chile, Colombia,  Perú, Venezuela y Puerto Rico, además de Argentina</em>), fotos y otro documental  sobre la grabación del álbum. Como bonus track se incluyen los videoclips de <strong>“<em>Crimen</em>”</strong>, <strong>“<em>La Excepción</em>”</strong> y <strong>“<em>Adiós</em>”</strong>, como así también la  versión en vivo de “<em>Crimen</em>” junto a <strong>Ricardo  Mollo</strong>.</p>
            <p>El  sábado 17 de mayo de 2008, Gustavo Cerati participó junto a otros artistas del <strong>Festival Alas</strong>, organizado a beneficio  de los chicos carenciados de América Latina. En Costanera Sur y frente a más de  150 mil personas, Cerati compartió escenario con <strong>Fito Páez</strong> con quien hicieron los temas <strong>“<em>Crimen</em>”</strong>, <strong>“<em>Gente sin swing</em>”</strong>, <strong>“<em>Puente</em>”</strong> y <strong>“<em>Ciudad de pobres corazones</em>”</strong>. Cerati volvió a pisar el escenario,  esta vez invitado por <strong>Shakira</strong> con  quien tocó <strong>“<em>En la ciudad de la furia</em>”</strong>.</p>
            <p>El 9 de septiembre, MTV Latinoamérica dio a conocer los nominados  para la <strong>7ª entrega anual de Los Premios MTV Latinoamérica 2008.</strong><br />
                <strong>Gustavo Cerati</strong> contó con dos nominaciones: <strong>Mejor Solista y  Mejor Artista Rock.</strong> Por su parte, <strong>Soda Stereo </strong>fue <strong>nominado</strong> como <strong>Mejor Gira de Reencuentro </strong>(Me verás volver). La <strong>ceremonia de  premiación</strong> fue transmitida en vivo desde el Auditorio Telmex de Guadalajara  - Jalisco, México-  <strong>el jueves 16 de  octubre</strong>.</p>
            <p>El siguiente 12 de septiembre, fueron anunciados los nominados a la  9ª edición de los Grammy Latinos. La  canción <strong>El mareo</strong>, que  pertenece a Mar dulce, el segundo álbum del grupo Bajofondo, en la que Gustavo Cerati fue invitado a grabar,  obtuvo una nominación como Mejor  Canción Alternativa. </p>
            <h5 id="fn">Fuerza Natural</h5>
            <p>En octubre Gustavo viajó a Bahamas para trabajar en algunas  canciones del próximo disco de Shakira, participando como autor y productor. A  su regreso,  retomaría la composición de  su próximo disco y comenzaría los ensayos previos a la grabación. </p>
            <p>El sábado 8 de noviembre Gustavo Cerati  fue invitado por <strong>Bajofondo Tango Club</strong> a participar de su presentación en  el Main Stage de <strong>Creamfields</strong>, el cual se realizó en el Autódromo de  Buenos Aires. La banda liderada por Gustavo Santaolalla interpretó junto a  Cerati <strong>“El Mareo”</strong>, segundo single de Mar Dulce. 35 mil personas habían  ingresado en el complejo, y ovacionaron su presentación. La canción  fue grabada en <em>Electric Lady Studios </em>(<em>Nueva York</em>) y cuenta con la  participación de Cerati en la versión original.</p>
            <p>En la última etapa del año, ya habían participado de la grabación  Leandro Fresco <em>(teclados)</em>, Fernando Nalé <em>(bajo)</em>, Fernando Samalea <em>(batería y percusión)</em>, Gonzalo Córdoba <em>(guitarras)</em>, Anita Álvarez  de Toledo <em>(coros)</em> y &quot;Bolsa&quot; González <em>(batería)</em>.</p>
            <p>El disco grabado y mezclado en <strong>Unísono</strong> por el ingeniero de sonido Héctor Castillo, quien trabajó con<em> Pete Townsend, David Bowie y Lou Reed, </em>entre otros.</p>
            <p>Durante el mes de marzo de 2009, <strong>Gustavo</strong> viajó a Estados  Unidos para realizar algunas <strong>grabaciones de su nuevo disco</strong> de estudio en <em>Stratosphere Sound </em>y <em>Looking Glass </em>junto al <strong>ingeniero de  sonido Héctor Castillo</strong>.<br />
                <br />
                A  los músicos ya anunciados en la grabación <strong>se sumaron en Nueva York </strong>las  colaboraciones de: <strong>Sterling Campbell </strong>(en batería)<strong> </strong>quien fue miembro de Duran Duran, colaboró con  David Bowie y The B-52's, entre otros; <strong>Didi Gutman, tecladista </strong>de  Brazilian Girls; <strong>Byron Isaacs en lap steel y bajo </strong>(fue músico entre  muchos otros de Willie Nelson, Elvis Costello y Ryan Adams) <strong>y Glenn Patscha  en piano y órgano </strong>(grabó con Roger Waters, Laurie Anderson, Elvis Costello  y por mencionar los más destacados).</p>
            <p>"<em>Fuerza Natural</em>" será editado por <strong>Sony  Music Argentina </strong>y estará en las bateas el 1ro de Septiembre de 2009</p>
            <p>El 20 de julio se estrena <strong><em>Déjà  vu,</em></strong> el esperado primer single de su nuevo disco <strong><em>Fuerza Natural</em></strong> y se anuncia que el lanzamiento internacional será el 1 de septiembre.</p>
            <p>Por fin llega entonces el 1 de  septiembre y es lanzado el tan esperado disco.</p>
            <p><strong>&quot;Fuerza Natural&quot; </strong>es mucho mas que un disco.&nbsp; Es  un viaje emocionante.<strong>&nbsp; </strong>Una sucesión de historias rodeadas por la  magia del folk, la vibración del pop, el poderío del rock, la manipulación  electrónica, el color de la psicodelia y la calidez de los sonidos acústicos.<br />
                <br />
                En<strong> &quot;Fuerza Natural&quot; Gustavo  Cerati</strong> resume su trayectoria y propone nuevos recorridos, planteando en  su trayecto diversos matices, climas y estados de ánimo.<br />
                <br />
                A lo largo de los 13<strong> </strong>temas que componen este álbum, <strong>Cerati</strong> da  rienda a su lírica y a todo su poder compositivo, en lo que él mismo considera  es su <em>&quot;disco más libre&quot;</em>.&nbsp; La definición de <strong>&quot;álbum&quot;</strong> justamente aplica en este nuevo trabajo como un concepto absoluto. El disco  concebido como una pieza artística, tal y como lo entendieron aquellos artistas  de fines de los '60 que, de algún modo, inspiraron este trabajo.<br />
                <br />
                Los temas que lo integran son: <em>Fuerza Natural; Déjà vu; Magia; Amor sin  Rodeos; Tracción a Sangre; Desastre; Cactus; Rapto; Naturaleza Muerta; Dominó;  Sal; Convoy y He Visto a Lucy</em>.
                <br />
                <strong>&quot;Fuerza Natural&quot;</strong> es lanzado en tres formatos: <strong>CD</strong>,<strong> vinilo</strong>, y<strong> Musicpass</strong>. El CD incluye los 13 <em>tracks</em> en un solo  disco, mientras que la edición en vinilo está compuesta por 2 LP's. La novedad  es que <strong>&quot;Fuerza Natural&quot;</strong> es que es el primer álbum en Argentina  en editarse en <strong>Musicpass</strong>, <u>un nuevo formato de música digital en alta  calidad</u>. Se trata de una tarjeta que permite descargar música original para  celulares, <em>notebooks</em>, pc y reproductores de audio compatibles con mp3. </p>
            <p>El elogiado álbum de Gustavo Cerati, se ubicó a menos de una semana de su  lanzamiento en el puesto #1 de los rankings de ventas en Argentina, México,  Colombia y Chile.<br />
                <br />
                Asimismo <strong>&quot;Fuerza Natural&quot;</strong> fue el disco más vendido de la  tienda latina de iTunes en Estados Unidos durante la semana de su debut y superó  el galardón de Disco de Platino en Argentina a menos de dos semanas de su  edición y la edición &nbsp;<strong>Musicpass</strong> de <strong>&quot;Fuerza Natural&quot; </strong>debutó  en el TOP 10 de ventas de la principal tienda de discos de Argentina.</p>
            <p>En noviembre se estrena <strong>“Déjà vu” . </strong>video del primer corte.<br />
                Filmado en locaciones de la provincia de &nbsp;Salta durante 2  días del mes de Septiembre, fue producido y dirigido por Landia. El clip fue  realizado íntegramente en formato 16   mm.<br />
                <br />
                Este primer video del nuevo disco de Gustavo Cerati ha sido concebido detrás de una idea  original&nbsp; basada en armar con todos los temas del disco un único y <em>gran  video clip</em> en forma de <em>película o trayecto fílmico.&nbsp; </em>Dicha <em>película</em> unirá visual y musicalmente, en diferentes entregas, todos los tracks de <strong>FUERZA  NATURAL</strong> conformando una gran historia… un viaje surreal y fantástico de Gustavo Cerati a través  de diferentes espacios, tiempos, lugares y personajes.<br />
                <br />
                <strong>“Déjà vu”</strong>, la primera entrega, es un fragmento de este trayecto en el  cual Cerati viaja&nbsp; con una extraña caja luminosa a través de un paisaje  solitario e ira de a poco encontrándose con una imagen, que se repite como un  extraño deja vu, de una mujer que baila ensimismada y alocadamente delante de  un tren plateado y luminoso que pasa detrás de ella como un loop&nbsp;  infinito.<br />
                Paralelamente se anuncia la gira 2009 que lo llevaría en esta  primer etapa a México, Chile, Uruguay y Argentina.</p>
            <p>El segundo corte, <strong>Rapto </strong>comienza  a rotar en noviembre y su clip<strong>&quot;Rapto&quot;,</strong> se estrena un mes despues. Filmado durante dos días en  rutas y locaciones &nbsp;de &nbsp;la provincia de Buenos Aires y en un viejo  aeropuerto abandonado utilizado como set principal.<br />
                <br />
                Este segundo clip es también parte del único y <em>gran video clip</em> en forma  de <em>trayecto fílmico</em> que comenzó con <strong>&quot;Déjà vu&quot;. </strong>Dicha <em>película</em> unirá visual y musicalmente, en diferentes entregas, todos los tracks de <strong>FUERZA  NATURAL</strong> conformando una historia cinematográfica que narrará un viaje  de <strong>Gustavo Cerati</strong> por diferentes paisajes, historias y <em>moods</em> de este nuevo disco. </p>
            <p>En <strong>&quot;Rapto&quot;</strong>comienzan a aparecer&nbsp;y repetirse  ciertos temas e ideas que ya fueron planteadas en <strong>&quot;Déjà vu&quot;, </strong>y  que se irán repitiendo y retomando &nbsp;a lo largo de &nbsp;todos los videos.  &nbsp;&nbsp;El auto, el viaje, &nbsp;un misterioso rapto y robo de una caja; y  un bar extraño de <em>freaks</em> donde una banda que emula a unos <em>&quot;ZZ  Top pampeanos&quot;;</em> realiza un divertido <em>playback</em> de la canción.<br />
                <br />
                El video contó con la actuación especial de mas &nbsp;de 20 actores, entre  ellos &nbsp;varios músicos y amigos de Gustavo Cerati como <em>Anita  Alvarez Toledo, Gonzalo Córdoba, Flavio Echeto, Santiago Contreras, Elisinha de  Corral y Cintia Rosenfeld.</em><br />
                <br />
                El video fue producido por Andy Fogwill y LANDIA, y dirigido por Maxi Blanco. </p>
            <p>Paradójicamente, el esperado  show de presentación de Fuerza Natural en Buenos Aires, se vió postergado 24  horas por un temporal que mantuvo a la ciudad en alerta meteorológica durante  el sábado 19.<br />
                Finalmente y después de un radiante día, el domingo 20 a las 20:30 horas ante 25  mil personas Gustavo   Cerati dio inicio a la presentación de su quinto álbum.<br />
                Acompañado por Richard Coleman, Gonzalo  Córdoba, Leandro Fresco, Fernando Nalé, Fernando Samalea y Anita Álvarez de  Toledo, Gustavo abrió el show con “Fuerza Natural”, el tema que da nombre a su  último trabajo, y desató la euforia del público.<br />
                En la primera parte del concierto  Gustavo presentó las canciones de su último disco, continuando con “Magia,  “Déjà  Vu”, “Desastre”, “Rapto” – nuevo  corte de difusión – , “Amor sin rodeos”, “Tracción a Sangre”, “Cactus”,  “Naturaleza Muerta”, “Dominó”, “Sal”, “Convoy” y “He visto a Lucy” en el que  participó como invitado Gillespi y un grupo de <em>brasses</em><br />
                Luego, según sus propias palabras, como  homenaje a Mercedes Sosa, tocó “Zona de promesas”, tema que la cantora eligió  grabar en su última producción discográfica.<br />
                Después de tocar por más de una hora,  en la segunda parte del show Cerati recorrió los mejores temas de su  trayectoria solista: “Pulsar”, “ Te llevo”, “Marea de Venus”, “Crimen”, “Paseo  inmoral”, “Cosas Imposibles”,“La Excepción”, “Adiós”.<br />
                En los <em>bises</em>: “Puente”, “Lago en  el cielo”, “Vivo” y “Jugo de Luna” provocando una fuerte ovación del público y  por último, casi emulando el <em>track</em> oculto del cd: “#”<br />
                Con la puesta de Martin Phillips (el mismo que se encargó de la impactante  escenografía de la gira de Soda Stereo y trabajó para artistas internacionales  como Daft Punk y Nine Inch Nails), el diseño de vestuario de Manu Morales, el  sonido de Adrián Taverna y las visuales en vivo de Nicolás Bernaudo, Gustavo se  lució en durante dos horas y media en un show impresionante. <br />
                La etapa 2009 de la gira “Fuerza  Natural” 2009, que continuará en 2010, alcanza en esta etapa a recorrer 7  ciudades (Monterrey, Guadalajara, Distrito Federal de México, Santiago de  Chile, Montevideo, Córdoba y Buenos Aires) y casi 100 mil espectadores,  recogiendo halagos  de los seguidores y  reconocimiento de los medios:<br />
                <em><a href="http://www.milenio.com/node/325472">Para anotarse  un ‘jonrón’ en Monterrey, a Gustavo Cerati no le hizo  falta ni un bate, ni terceras bases y menos pelotas de beisbol. Bastó con su  voz y talento inigualable para echarse al público a la bolsa e iniciar con el  pie derecho su Tour 2009</a>. (Milenio/Monterrey, México)</em><br />
                <em><a href="http://www.elbravomatamoros.com/noticias.aspx?seccion=5&amp;noticia=174846">La música de  Gustavo Cerati  es como una habitación compartida por dos épocas: Una que siempre está  llegando; otra que nunca se ha marchado...acompañado de una banda de músicos  virtuosos, no defraudó a quienes llegaron para quedarse dentro de su habitación  que mantiene el confort de siempre y donde el anfitrión puede decir: ¡Gracias  por venir! y ¡buen viaje!.</a> (El Bravo/Monterrey, México).</em><br />
                <em><a href="http://www.milenio.com/node/326718">El músico  argentino, figura indispensable en la historia del rock hispano y favorito en Guadalajara, se presentó anoche en el  auditorio Telmex logrando emocionar a más de seis mil seguidores que no  faltaron a la cita</a>. (Milenio/Guadalajara, México). </em><br />
                <em><a href="http://www.exonline.com.mx/diario/noticia/funcion/musica/gustavo_cerati_llega_con_fuerza/790038">Fue una noche  emotiva, la cual disfrutaron casi 10 mil personas que permanecieron de pie  durante dos horas y 20 minutos. En ella, el argentino hechizó a sus seguidores  gracias a sus habilidades musicales y a su repertorio de 25 canciones, el cual  incluyó sus éxitos como solista</a>. (Excelsior/Distrito Federal, México)</em><br />
                <em><a href="http://diario.elmercurio.cl/detalle/index.asp?id={39a68958-c64a-4b7d-80cf-bd526e2481e1}">Gustavo Cerati</a></em><a href="http://diario.elmercurio.cl/detalle/index.asp?id={39a68958-c64a-4b7d-80cf-bd526e2481e1}"><em> tuvo un ovacionado regreso</em></a><em> (El Mercurio/  Santiago de Chile, Chile)</em><br />
                <em><a href="http://www.lavoz.com.ar/09/12/12/secciones/economia/nota.asp?nota_id=575286">Gustavo Cerati</a></em><a href="http://www.lavoz.com.ar/09/12/12/secciones/economia/nota.asp?nota_id=575286"><em>, con el universo a su  favor. Exquisito: ofreció un concierto  de alto vuelo con preeminencia folk y una iluminación de ensueño (La voz del interior/ Córdoba, Argentina) </em></a><br />
                <em><a href="http://www.clarin.com/diario/2009/12/21/sociedad/s-02105250.htm">Cerati  exhibió anoche los temas de su último disco, Fuerza Natural. Y demostró que su  poder de seducción, como el de sus canciones, se mantiene intacto…</a></em> <a href="http://www.clarin.com/diario/2009/12/21/sociedad/s-02105250.htm"><em>A esta altura no es novedad hablar del  cuidado de las puestas del músico.</em></a><em> (Clarín/Buenos Aires, Argentina)</em></p>
            <br />
            {// eslint-disable-next-line
            <p>Fuente: <a href="http://cerati.com/" target="_blank"><em>cerati.com</em></a></p>
            }
        </>
    )
}
export { BioGustavo };