function BioSoda() {
    return (
        <>
            <h2>Historia</h2>
            <h3>Contenido</h3>
            <table className="table">
                <tbody>
                    <tr>
                        <td><a href="#estereotipos">De Los Estereotipos a Soda Stereo (1982-1984)</a></td>
                    </tr>
                    <tr>
                    <td><a href="#debutDiscográfico">Debut discográfico y banda revelación del verano (1984-1985)</a></td>
                    </tr>
                    <tr>
                        <td><a href="#nadaPersonal">Nada Personal: consagración en Obras (1985-1986)</a></td>
                    </tr>
                    <tr>
                        <td><a href="#conquista">La conquista de América (1986-1990)</a></td>
                    </tr>
                    <tr>
                        <td><a href="#giro">Giro hacia el rock duro: Canción animal (1990-1992)</a></td>
                    </tr>
                    <tr>
                        <td><a href="#dynamo">El sónico Dynamo, posterior pausa (1992-1995)</a></td>
                    </tr>
                    <tr>
                        <td><a href="#reanudación">Reanudación, experimentación electrónica (1995-1997)</a></td>
                    </tr>
                    <tr>
                        <td><a href="#giraRetiro">Gira de retiro (1997)</a></td>
                    </tr>
                    <tr>
                        <td><a href="#postSoda">Post-Soda (1997-2007)</a></td>
                    </tr>
                    <tr>
                        <td><a href="#meVerásVolver">Gira Me Verás Volver (2007)</a></td>
                    </tr>
                    <tr>
                        <td><a href="#muerteGustavo">Muerte de Gustavo Cerati y Sép7imo Día (2008-2020)</a></td>
                    </tr>
                    <tr>
                        <td><a href="#graciasTotales">Gracias Totales (2020-2022)</a></td>
                    </tr>
                </tbody>
            </table>
            <br />
            <h4 id="estereotipos">De Los Estereotipos a Soda Stereo (1982-1984)</h4>
            <p>A comienzos de los años 1980, Gustavo Cerati, de 22 años, y Héctor «Zeta» Bosio, de 23 años, compartían los mismos gustos y sueños musicales y comenzaron una búsqueda para integrar un grupo punk rock inspirado en The Police, que visitó Argentina en 1980, y The Cure, con temas propios en español. Formaron, sucesivamente, el grupo Stress, junto a Charly Amato, Sandra Baylac y el baterista Pablo Guadalupe, y Proyecto Erekto junto a Andrés Calamaro, que no cubrieron sus expectativas.</p>
            <p>En el verano de 1981, ambos coincidieron en Punta del Este (Uruguay): Cerati con su Sauvage,19 una banda de covers de música disco, y Bosio con The Morgan, una banda integrada también por Sandra Baylac, Hugo Dop, Christian Hansen, Pablo Rodríguez,20 Charly Amato, Osvaldo Kaplan y Andrés Calamaro.21 Debido a una serie de peripecias, Cerati y Bosio establecieron un estrecho vínculo musical y de amistad que los llevó a comenzar a tocar juntos.</p>
            <p>Cerati comentaba de este modo esos primeros instantes:
                La fecha es el año 82, Guerra de las Malvinas. Yo trabajaba en una agencia como junior. Había estudiado Publicidad en la Facultad y con Zeta teníamos asignaturas en común, pero no nos conocíamos mucho. Yo estaba tocando con una banda de blues y rock de la zona de Flores, al oeste de Buenos Aires y él con un grupo que hacía covers. En el verano me fui a Punta del Este con un grupo de música disco, un grupo para ganar dinero. Hacía cosas de The Commodores, de guitarrista rítmico y cantaba con un par de inglesas que hacían las voces. El lugar donde tocábamos quebró y nos quedamos sin un peso en Punta del Este. Intentamos vender todo lo que estaba en la discoteca, porque la dueña se fugó. Nos mandó unos cheques sin fondos, así que empezamos a vender todo. Alquilamos el piano para poder quedarnos, porque estaba bueno ese verano. Uno de los pocos buenos, porque había gente sin plata, como nosotros. En otro lugar de Punta del Este estaba Zeta tocando con un grupo que se llamaba The Morgan. Como no tenía dónde quedarme, me fui con ellos, y ahí empezó mi relación con Zeta. Planeamos la idea de tener un grupo, y luego en las clases nos dedicábamos a buscar nombres de grupos, a escuchar música y cualquier cosa menos a lo que teníamos que hacer.
                Pasamos largo tiempo buscando otras personas para hacer algo, y finalmente nos quedamos Zeta y yo con los teclados de Andrés Calamaro, con quien formamos una banda que se llamó Proyecto Erekto, que era un grupo de tecno. Pero nuestra idea era armar un grupo de rock. Había llegado The Police, una de nuestras mayores influencias, a Argentina (en diciembre de 1980) y teníamos que ir todos a verlos.
            </p>
            <p>Por entonces Carlos Ficcichia, nombre legal de Charly Alberti, llamaba insistentemente por teléfono a María Laura Cerati, la hermana de Gustavo a quien había conocido en las piletas de River Plate, para invitarla a salir, pero ésta pensaba que era un «pesado» (molesto) y no lo quería atender. En una oportunidad fue Gustavo quien atendió una llamada de Charly para su hermana y entablaron una conversación de compromiso en la que Carlos contó que tocaba la batería y que era hijo de un famoso baterista de jazz, Tito Alberti, autor además de la conocida canción infantil «El elefante trompita». A la semana, Gustavo y Zeta decidieron visitar a Charly Alberti (cuatro años más joven que Cerati) para escucharlo tocar en la batería. Cerati y Bossio quedaron impresionados por el equipamiento y la formación de Alberti y los tres se sorprendieron de tener como referencias a las mismas bandas británicas: «fue amor a primera vista», han dicho Bossio y Alberti sobre aquel encuentro. Luego de que Gustavo le dijera a Charly «¡el pelo te lo cortás!» la banda quedó formada.
            </p>
            <p>Después de examinar algunas ocurrencias (Aerosol, Side Car) adoptaron el nombre de Los Estereotipos, debido a una canción de The Specials que les apasionaba a los tres y que utilizaron unos meses. De esa primerísima época data un demo, grabado en cuatro canales, en donde ejecutó guitarras Richard Coleman que fue integrante oficial de la banda durante muy poco tiempo en aquellos días de 1982. Los temas del demo fueron los siguientes: «¿Por qué no puedo ser del Jet-Set?», «Dime Sebastián» y «Debo soñar» (de Ulises Butrón), acompañados por Daniel Melero en teclados y Ulises Butrón en guitarra. Luego surgieron los nombres «Soda» y «Estéreo», dando como resultado «Soda Stereo», y manteniendo así parcialmente el nombre inicial.
            </p>
            <p>Sobre el origen y sentido de la palabra «soda» explicaba un periodista:
                Ellos dicen que hacen música con burbujas. Pero en lugar de tratarse de lujosas burbujas de champagne, afirman haber asumido la representatividad cotidiana y popular del sifón.
            </p>
            <p>Tito Alberti contó la siguiente anécdota:
                Un día les pregunté cómo se iban a llamar y me dijeron: Soda Stereo. Yo estaba medio hinchado y les dije: ¿Por qué no le ponen Sifón Drago? No me hablaron por seis meses. Y adónde llegaron, ¿no?.
            </p>
            <h4 id="debutDiscográfico">Debut discográfico y banda revelación del verano (1984-1985)</h4>
            <p>El videoclip «Dietético» fue difundido por el programa Música Total de Canal 9 y tuvo un impacto considerable. Poco después, en la segunda mitad de 1984, la banda grabó su primer álbum, Soda Stereo, con la producción de Federico Moura, vocalista de Virus, quien había establecido una estrecha relación artística con Cerati que se expresó en el acercamiento entre ambas bandas. La grabación se realizó en los obsoletos estudios de CBS en la calle Paraguay y si bien el resultado obtenido fue un sonido más frío que el de las presentaciones en vivo, los músicos quedaron conformes. El trío fue acompañado por Daniel Melero en teclados (autor de la balada «Trátame suavemente») y Gonzo Palacios en saxo, con la categoría de «músicos invitados», una práctica que adoptarían en lo sucesivo y que en algunos casos resultaron ser verdaderos miembros de la banda, denominados por los fanes y los medios con el título de «cuarto Soda».</p>
            <p>La presentación oficial del álbum se realizó el 1 de octubre y fue organizada por Ares como si se tratara de un espectáculo, algo que nunca se había hecho en la Argentina hasta entonces. El lugar elegido fue un local céntrico de comida rápida de la cadena Pumper Nic (Suipacha entre Corrientes y Lavalle), la más popular entre los jóvenes argentinos de los 80, y se proyectó el videoclip. La repercusión en la prensa fue buena, aunque momentánea. Al día siguiente el diario Clarín publicaba las siguientes declaraciones de la banda:
                Somos un conjunto dietético, buscando el paraíso estético, Nuestra música es dietética. Hace adelgazar comiendo, pero ante cualquier duda consulte a su médico. Tratamos de mantener los cuerpos sanos y las mentes desaceleradas.
            </p>
            <p>La creciente adhesión del público se fue manifestando en su actuación en escenarios cada vez más amplios: primero La Esquina del Sol en Palermo; el Recital de Los Lagos (1 y 2 de diciembre), su primer escenario multitudinario, junto a otras bandas de primera línea y conducción de Badía; y finalmente su primera actuación en el teatro Astros del 14 de diciembre de 1984 donde el disco fue presentado por primera vez en vivo. La estética fue preparada por Alfredo Lois, quien para la ocasión decidió colocar 26 televisores prendidos y fuera de sintonía con el fondo musical del tema «Sobredosis de TV». Esto, sumado a una gran cantidad de humo, dio un inusual y atrapante efecto visual. Para fin de año Soda Stereo ya era aceptado como la revelación del año, aunque figuraron segundos en la revista Pelo. Por entonces aparecen los primeros grupos de fanes y detractores.
            </p>
            <p>A comienzos de 1985, la banda cambió de agencia, dejando la de Rodríguez Ares por Ohanián Producciones, dirigida por Alberto Ohanián e incorporaron como invitado en teclados a Fabián «Vön» Quintiero (quien luego tocara con Charly García y Los Ratones Paranoicos), uno de los músicos «invitados» que habría de recibir el título de «cuarto Soda».
            </p>
            <p>El 26 de enero salieron de Buenos Aires para tocar en el Festival Rock In Bali de Mar del Plata y el 17 de marzo en el Festival Chateau Rock '85 realizado en el Estadio Chateau Carreras de la provincia de Córdoba. La biografía oficial de la banda concede gran importancia a esta presentación indicando que actuaron ante 15 mil personas y que fueron la revelación del mismo. Sin embargo las fuentes cordobesas indican que hubo la mitad de gente y que «Raúl Porchetto fue el más ovacionado y los Soda pasaron casi inadvertidos porque su primer disco llevaba apenas unos meses de editado». De todos modos la actuación en el Chateau inició una relación personal de la banda con los jóvenes cordobeses y marcó el momento en que la banda comenzó a despegar hacia el estrellato nacional.
            </p>
            <p>El éxito del grupo comenzaba en un momento muy particular, relacionado, por una parte con el retorno a la democracia en Argentina (10 de diciembre de 1983) y por el otro con las nociones de posmodernidad y el modo en que los jóvenes de la década de 1980 intentaban pensar su papel en una sociedad democrática, que salía de una cruenta dictadura y de una guerra. Años más tarde Zeta Bosio reflexionaba de este modo sobre ese momento:
                La democracia producía la adrenalina de algo nuevo, algo que estaba ocurriendo, que sabía que nos iba a modificar sin saber bien cómo. Había más aire para hacer cosas y divagar, y nosotros éramos una banda de pibes que teníamos ganas de hacer lío. Nuestra atención estaba en el punk y en tratar de mostrar que había otra cosa que era más directa.
            </p>
            <p>Los días 21, 22 y 23 de junio de 1985, volvieron a presentarse en el Teatro Astros de Buenos Aires, adelantando algunos temas de lo que meses más tarde sería su segundo disco de estudio, titulado Nada personal. Para estas presentaciones volvieron a preocuparse por mostrar una estética llamativa desde el escenario: armaron una playa con dunas y palmeras de telgopor y olas de papel de celofán.
            </p>
            <p>El 13 de octubre de ese año, se presentaron ante el gran público de Buenos Aires en el marco de la tercera noche del Festival Rock & Pop realizado en el Estadio José Amalfitani del club Vélez Sarsfield, compartiendo cartel con INXS, Nina Hagen, Charly García, Virus y Sumo, entre otros. Para ese entonces Fabián «Vön» Quintiero y el Gonzo Palacios ya eran «invitados estables».
            </p>
            <h4 id="nadaPersonal">Nada Personal: consagración en Obras (1985-1986)</h4>
            <p>Su segundo álbum, Nada Personal, fue editado en noviembre de 1985. Durante el verano el grupo realizó una gira de conciertos por los centros turísticos argentinos, tocando en Mar del Plata, Villa Gesell, Pinamar, Las Grutas, y Lomas de Zamora (Salón Go-es) sumando además un concierto consagratorio en el Festival de La Falda, en Córdoba.
            </p>
            <p>En abril de 1986, Soda Stereo llegó al Estadio Obras, conocido como «el templo del rock argentino».
            </p>
            <p>En abril, decidieron presentar oficialmente el álbum con un concierto en el Estadio Obras Sanitarias de Buenos Aires. Realizaron cuatro históricas funciones a lleno total sumando 20.000 espectadores, el 11, 12 y 13 de ese mes. Durante la primera de las tres funciones se filmó un vídeo en vivo de larga duración editado pocos meses después. Bobby Flores, el conocido crítico musical y cofundador de la revolucionaria radio Rock & Pop de Buenos Aires, terminaba de esta manera su crónica del recital:
                Nos hallamos frente a la más poderosa agrupación del país… El mejor parámetro para medir esta presentación es que se me hizo corto, parecía haber durado diez minutos; y la gente se quedó con ganas de más. La salida del estadio fue un murmullo general de las canciones de Soda Stereo. La lluvia, el tráfico cortado en la Avenida Libertador por los que salían y por los que entraban, el último pancho de la noche y una saludable sensación de bienestar, no dejan lugar para las dudas existenciales. Volví a colocar mi mandíbula en su lugar, y me fui cantando bajito Estoy Azulado, entre la lluvia por Libertador.
            </p>
            <p>A partir de esos conciertos las ventas del disco comenzaron a crecer aceleradamente, pasando del disco de oro, que habían conseguido durante el verano, hasta el platino, y llegando a doblar esa cifra en los meses siguientes. Sin abandonar los ritmos «bailables», este segundo LP logró más profundidad en las letras y madurez en las melodías. El disco significó la consagración definitiva de Soda Stereo ante el público argentino.
            </p>
            <p>En junio de 1986, luego de una gira nacional, el trío grabó su segundo videoclip con el tema «Cuando pase el temblor», nuevamente bajo la dirección de Alfredo Lois, en las ruinas del Pucará de Tilcara, en la provincia de Jujuy. El video, que completó la filmación de la presentación en el Estadio Obras, fue nominado como finalista del 12.° World Festival of Video and TV en Acapulco unos años después.
            </p>
            <h4 id="conquista">La conquista de América (1986-1990)</h4>
            <p>
                En 1986, los jóvenes chilenos recibieron a Soda Stereo como ídolos populares. La canción que expresó ese primer contacto fue «Nada personal», que se convirtió en un éxito radial.
            </p>
            <p>
                A fines de 1986, Soda Stereo realizó su primera gira latinoamericana, aún dentro de la presentación de Nada Personal. La banda se presentó en Colombia, Perú y Chile, con un éxito considerable.
            </p>
            <p>
                El éxito fue especialmente masivo en Chile, donde realizaron cuatro recitales en Santiago y uno en Valparaíso.
            </p>
            <p>
                En Perú, el grupo también obtuvo un éxito sorprendente para una banda de rock. Sus presentaciones en el Coliseo Amauta fueron inolvidables, generando una histeria colectiva comparable a la de los Beatles en el Shea Stadium.
            </p>
            <p>
                Cerati, desde su punto de vista, describió el impacto en Chile como sorpresivo y mencionó la explosión final durante el Festival de Viña del Mar en febrero de 1987. El grupo estaba feliz por el reconocimiento y la fama alcanzada.
            </p>
            <p>
                El 10 de noviembre de 1986, la banda lanzó su tercer álbum, "Signos". Este álbum fue un paso clave, ya que marcó un aumento en las expectativas y el éxito de la banda. Además, fue el primer disco del rock argentino en editarse en disco compacto.
            </p>
            <p>
                Soda Stereo realizó una gira extensa por Latinoamérica, incluyendo países como Ecuador, Uruguay y Chile. En Chile, su presentación en el Festival de Viña del Mar en febrero de 1987 les valió el premio Antorcha de Plata y los catapultó a la fama en toda la región.
            </p>
            <p>
                En abril de 1987, la banda batió récords de público en Paraguay con un recital en el Yacht y Golf Club Paraguayo. Mientras tanto, su álbum "Signos" alcanzaba el estatus de disco de platino en Argentina, Perú y Chile.
            </p>
            <p>
                El 2 de mayo, mientras se presentaban en la discoteca Highland Road de San Nicolás, Buenos Aires, ocurrió un derrumbe en el que murieron cinco jóvenes y hubo más de 100 heridos, mientras estaban tocando «Persiana Americana». Con una carga emocional muy fuerte, la banda tocó en Obras el 8 y 9 de mayo para presentar Signos en Buenos Aires. Como expresión de duelo, el grupo no utilizó la escenografía ni los juegos de iluminación que tenían preparados.
            </p>
            <p>
                Ese mismo año emprendieron una segunda gira por el continente con un repercusión aún mayor. Realizaron 22 conciertos en 17 ciudades frente a casi 350,000 personas, abriendo así la idea misma de un «rock latino», más allá de la nacionalidad de cada banda. Con el material grabado en los distintos puntos del viaje se realizó el disco en vivo Ruido Blanco (1987), considerado por la revista Rolling Stone de Argentina como el 5.º entre los mejores álbumes en vivo del rock argentino.
            </p>
            <p>
                Cuando llegaba 1988, Soda Stereo ya era la banda más importante del pop rock latinoamericano y se disponían a grabar su nuevo álbum, "Doble Vida". Este álbum, grabado enteramente en Nueva York, se convirtió en el primer disco de una banda argentina grabado íntegramente fuera de su país. El corte de difusión del disco y su vídeo, «En la ciudad de la furia», fue nominado en los MTV Video Music Awards de 1990 en la categoría de International Viewer's Choice - MTV Internacional.
            </p>
            <p>
                A estas alturas, Soda había conquistado un nuevo récord histórico: eran la primera banda argentina cuyos videoclips eran emitidos por el canal de televisión MTV, siendo que el canal transmitía en inglés. Luego de más de un año sin presentaciones en Buenos Aires, la banda volvió el 3 de diciembre de 1988 para presentar el álbum Doble Vida en Obras.
            </p>
            <p>
                Para coronar un gran año, el 27 de diciembre de 1988 cerraron el Festival Tres Días por la Democracia en Buenos Aires ante 150,000 personas. Con la cifra de un millón de discos vendidos, Soda Stereo inició una gira de presentación del nuevo disco que comprendió 30 shows en casi toda Argentina ante 270,000 espectadores durante los primeros días de 1989, seguida por una nueva gira latinoamericana que terminó de consagrar masivamente a la banda en México.
            </p>
            <p>
                A principios de 1990, la banda se presentó en el Estadio José Amalfitani, compartiendo cartel junto al dúo inglés Tears For Fears en un show ante 32,000 personas. El éxito continental llevó a la cadena MTV News europea a prestar atención a lo que estaba sucediendo en América Latina con el rock en español, dedicándole un programa especial al grupo, hecho sin antecedentes para un grupo de rock que no cantara en inglés.56
            </p>
            <h4 id="giro">Giro hacia el rock duro: Canción animal (1990-1992)</h4>
            <p>Mientras tanto, en Argentina la situación del rock local era muy distinta. La hiperinflación de 1989 afectó severamente a la industria musical argentina y le puso un freno a las prometedoras carreras de numerosas bandas de pop rock y new wave, las cuales estaban atadas a los designios de los grandes sellos discográficos. Esto provocó separaciones a nivel masivo en la escena nacional por la falta de oportunidades. Por otro lado, muchas de las nuevas bandas argentinas que se formaron a partir de esta época adoptaron un modelo de autogestión (siguiendo el precedente de bandas como Los Redondos), acaso como prevención para no volver a quedar atrapadas en la inactividad en caso de otra crisis económica. Como resultado de todos estos factores, el pop en Argentina tuvo una caída en 1989, y la escena nacional dio un giro hacia los géneros duros del rock, como el rock and roll, hard rock, blues, punk, heavy metal, rock alternativo y rock barrial. Los historiadores del rock argentino han destacado que Argentina incluso se adelantó dos años a Estados Unidos y el Reino Unido, ya que estos dos países hicieron el abandono del sonido de los '80 recién en 1991, con la explosión del grunge.</p>
            <p>En este contexto, en junio de 1990 Soda Stereo viajó a Estados Unidos para registrar una nueva placa en los Estudios Criteria de Miami, con la idea de dar un giro rotundo en su música. Del sonido que tenían en los '80, pasarían a un rock duro tomando como influencias a las bandas del rock argentino de los '70 que los miembros escuchaban durante su adolescencia (Pescado Rabioso, Color Humano, Vox Dei), pero además sumándole el presente: incorporaron las tendencias contemporáneas del rock anglosajón underground que preparaba la explosión global del grunge (Screaming Trees, Smithereens y Pixies). Para lograr este proyecto, contaron con el aporte conceptual de Daniel Melero y la participación de Andrea Álvarez y Tweety González (todos importantes músicos de la escena roquera argentina del momento) en calidad de invitados.</p>
            <p>El resultado fue el álbum Canción Animal (1990), considerado generalizadamente como uno de los mejores de la historia no solo del rock argentino sino de todo el rock iberoamericano. Allí se encuentra su canción más conocida: «De música ligera», además de otros clásicos de la banda como «Canción animal», «Cae el sol», «Un millón de años luz», «(En) El séptimo día» y «Té para tres».</p>
            <p>El nuevo álbum significó para la banda el acceso al público español, que se plasmaría en mayo de 1992 con presentaciones en las ciudades de Madrid, Oviedo, Sevilla, Valencia y Barcelona.</p>
            <p>El resultado de la gira española, comparado con el fervor que acostumbraban en Latinoamérica, les dejó un cierto sabor amargo, aunque sirvió como una sólida experiencia válida para equilibrar los elevadísimos puntos latinoamericanos que implicaban el peligro de dejarlos colgados en las alturas, lejos del contacto con lo terrestre. Dicho en pocas palabras: España no fue para nada un fracaso, pero estuvo lejos a los éxitos a los que los Soda estaban tan acostumbrados en Latinoamérica, y eso les vino bien.</p>
            <p>La Gira Animal (1990-1991) fue una gira maratónica y nunca repetida por ningún artista. En Argentina abarcó treinta ciudades, incluyendo lugares donde nunca se había presentado una banda de la envergadura de Soda Stereo (San Juan: Santa Fe de la Vera Cruz, Junín, Clorinda, Puerto Iguazú, Corrientes, Posadas, Chascomús, Mar del Plata, Comodoro Rivadavia, Trelew, Neuquén, Santa Rosa, Trenque Lauquen, Mendoza, Córdoba, Río Cuarto, Santiago del Estero, San Miguel de Tucumán, Salta, Rosario, Buenos Aires, Olavarría, Pergamino). Internacionalmente: Santiago de Chile, Asunción del Paraguay, Punta del Este, Bogotá, Medellín, Cali, Barranquilla, Barquisimeto, Caracas, Valencia, Mérida, San Cristóbal, México, D. F., Monterrey, Guadalajara, León Gto., Mexicali y Tijuana. La Gira Animal cerró con catorce funciones en el teatro Gran Rex de Buenos Aires, con capacidad para 3.300 personas, entonces un récord notable.</p>
            <p>En cada lugar se respetó la misma infraestructura de show, que para ese momento era inédita para un artista local.</p>
            <p>De los shows en el Gran Rex surgió el EP Rex Mix (1991) que incluía versiones en vivo grabadas en el último de esos recitales, en la noche del 9 de julio de 1991, y versiones remixadas junto al tema nuevo «No necesito verte (para saberlo)».</p>
            <p>El 14 de diciembre de 1991, se produjo el histórico recital de la Avenida 9 de Julio, en Buenos Aires. Soda Stereo sorprendió y se vio sorprendido reuniendo a más de 250 000 personas para escuchar a la banda en el marco del ciclo de recitales gratuitos realizados por la Municipalidad de Buenos Aires llamados Mi Buenos Aires Querido II, que además fue televisado en directo. La gente bailó enloquecida cada tema y los músicos fueron captados por una sensación de haber llegado a lo máximo, de que ya no quedaba nada por conquistar.</p>
            <p>Tras ese furor sobrevino un período de dispersión. Cerati explicaba por entonces:</p>
            <p>Es muy difícil encontrar objetivos claros después de semejante recepción. Estar parado ante tanta gente que corea tu nombre es una experiencia muy fuerte. Ahora hay que empezar de nuevo desde abajo.</p>
            <p>En ese momento Cerati comenzó, paralelamente a su trabajo con Soda, la producción de un álbum en conjunto con Daniel Melero, Colores Santos, el cual contó con aportes de músicos invitados como Flavio Etcheto y Carola Bony.</p>
            <h4 id="dynamo">El sónico Dynamo, posterior pausa (1992-1995)</h4>
            <p>A partir de este momento los miembros de Soda tomaron conciencia de que se encontraban en el centro de la escena, por lo que decidieron dar lugar a la experimentación musical e impulsar abiertamente lo que sería conocido como la «movida sónica». A fines de 1992, Soda Stereo lanzó su sexto álbum, Dynamo, presentado con seis recitales realizados en el Estadio Obras a fines de ese mismo año. Cada show contó con una banda distinta como invitados y así estuvieron de soporte Babasónicos, Juana La Loca, Martes Menta y Tía Newton. La «movida sónica», de la que también formarían parte Demonios de Tasmania y Los Brujos, por ejemplo, derivaría luego hacia el llamado «Nuevo rock Argentino», con Massacre, Attaque 77 y El Otro Yo.64</p>
            <p>Luego viene Dynamo (1992) que consistió en tomar Canción Animal y destruirlo. Es como si a Canción Animal lo hubiéramos metido dentro del agua. Y, a nivel sonoro, quisimos producir eso, las canciones tenían más que ver con algo hipnótico. La idea era remixarlo, mezclarlo con algo más dance e incluir algo más trance en nuestra música. Sé que quienes adoptaron ese disco lo quieren y a mí me pasa lo mismo. (Gustavo Cerati)23</p>
            <p>Dynamo no vendió como se esperaba, en gran medida porque el grupo decidió cambiar de compañía discográfica inmediatamente después de grabado. Sony entonces, no tenía intenciones de apoyar un grupo que emigraba y BMG no podía promocionar un producto de otra empresa.</p>
            <p>En noviembre de 1992, los Soda fueron protagonistas de un hecho inédito en la Argentina: la transmisión de TV en stereo. Los tres músicos más Tweety González (teclados) y Flavio Etcheto (trompeta) tocaron casi todo el álbum en el programa Fax en concierto, conducido por Nicolás Repetto por el El Trece de Buenos Aires. Con una puesta de luces y un sonido impecables Cerati cantó sobre pistas previamente grabadas de las canciones y reforzaron en vivo guitarras, bajo y batería.65</p>
            <p>En enero de 1993, emprendieron su sexta gira latinoamericana, el Dynamo Tour, visitando México, Chile, Paraguay y Venezuela. Sin embargo, el 29 de marzo de 1993, tras dar un recital en Ecatepec, Estado de México, Cerati se bajó de la gira y voló hacia Chile, lo que provocó la cancelación de fechas de la gira programadas para Estados Unidos, España y otros países. Su actitud se debió a muchos factores:55 cansancio con la banda, deseos de un proyecto solista (que se plasmaría en el álbum Amor amarillo) y acompañar el embarazo de su mujer Cecilia Amenábar, que finalmente daría luz a Benito Cerati.</p>
            <p>A partir de entonces Soda entró en una pausa prolongada, y la falta de novedades llevó a que muchos dijeran que la banda se había separado, algo que fue desmentido por los miembros. Pero, al no realizar recitales, la banda igualmente yacía en una situación de «limbo».55</p>
            <p>En los dos años siguientes los miembros dieron pasos por caminos separados. Cerati encaró su primer proyecto enteramente solista y en 1993 lanzó el álbum Amor Amarillo, aunque dijo que no tenía la intención de seguir una carrera en solitario. Bosio se convirtió en un baluarte de las jóvenes bandas del rock sónico, siendo productor de Peligrosos Gorriones y Aguirre; pero se retiró de la escena pública tras el 4 de julio de 1994, cuando sucedió un trágico accidente donde perdió la vida su hijo Tobías, y su otro hijo, Simón, sufrió quemaduras. Alberti profundizó en proyectos personales relacionados con la informática y las novedades tecnológicas, investigando las posibilidades que traía la naciente internet; además formó una banda llamada Plum junto a su novia Deborah de Corral, llegando a lanzar un álbum homónimo en 1995.55</p>
            <p>A finales de 1994 se editó el álbum Zona de Promesas, un compilado de remixes de clásicos temas de la banda más una homónima canción nueva.</p>
            <h4 id="reanudación">Reanudación, experimentación electrónica (1995-1997)</h4>
            <p>A inicios de 1995, después de un distanciamiento de dos años, los Soda se volvieron a juntar para ver cómo estaba el clima entre ellos y empezaron una serie de ensayos. En ellos, Gustavo introdujo las herramientas tecnológicas que había empleado en sus álbumes solistas, como los secuenciadores y samplers. Luego de un tiempo tenían listos 25 temas para un álbum doble, donde el primer disco sería de canciones estándar, y el segundo disco sería de instrumentales electrónicos. Pero el sello discográfico no estaba dispuesto a aceptar que una banda que hubiese estado tanto tiempo inactiva le planteara un proyecto semejante, y los Soda debieron hacer una selección entre esos 25 temas para ubicarlos en un solo disco. A pesar de todo, sentían que al álbum le faltaba un hit que sostuviera las canciones experimentales y electrónicas, y no confiaban en el tema más radiable que tenían preparado, «Paseando por Roma», porque creían que le faltaba más contundencia. Fue entonces que durante un ensayo, a Gustavo le salió «Ella usó mi cabeza como un revólver»: fue la puntada final del disco.66</p>
            <p>Luego de tres años desde su anterior álbum de estudio, el trío volvió al mercado con Sueño Stereo, su séptimo y último álbum de estudio. Lanzado el 29 de junio, velozmente se transformó en disco de platino con el éxito gracias a temas como «Zoom» y «Ella usó mi cabeza como un revólver», el videoclip de este último fue elegido por la MTV como Video de la Gente (latino) en 1996, máximo reconocimiento continental del rock latinoamericano antes de que se establecieran los Premios MTV Latinoamérica en 2002. Obtuvieron en 1995 el Premio Konex de Platino por su trayectoria en esa última década como la mejor banda de rock de la Argentina.</p>
            <p>Sueño Stereo necesitó dos años y medio para concebirse. Sería ilógico decir que este álbum es la obra maestra de Soda Stereo, pero era lo más real del grupo en ese momento, porque estábamos despojados de la necesidad de tener un futuro de grupo, o de ser el mejor durante otros diez años. Ya habíamos pasado por muchas cosas y el grupo se sentía a sí mismo como clásico. Por otro lado estábamos muy orgullosos de lo que había promovido Dynamo y su lectura posterior. Entonces, Sueño Stereo tenía la presión del no presionarnos. El grupo era un proyecto que tenía que dar algo importante, no podía ser un disquito. Además, era volver a encontrarnos después de un tiempo y dejar que la música fluyera, sin pensar demasiado en que teníamos que dar un paso o algo así. Al final, Sueño Stereo es una de los discos más innovadores dentro de nuestra carrera, sin habérselo propuesto. Por su combinación sonora, por sus letras, por su sonoridad. (Gustavo Cerati)67</p>
            <p>El álbum fue el eje de la extensa Gira Sueño Stereo, iniciada el 8 de septiembre en el Teatro Gran Rex de Buenos Aires, recorriendo Venezuela, Colombia, Perú, Panamá, México y Estados Unidos (Los Ángeles, Chicago, Nueva York y Miami), y cerrándola el 24 de abril de 1996 en el Teatro Teletón de Santiago de Chile. Realizaron un recital gratuito para el festejo del 113.er aniversario de la ciudad de La Plata (capital de la provincia de Buenos Aires) ante 367 294 personas, con Julio y Marcelo Moura (ex Virus) como invitados.</p>
            <p>Buscamos formas de volver a ensamblarnos, porque estábamos fuera del training y del vértigo que teníamos… yo creo que a nosotros nos pasó como a esas parejas que tuvieron una pasión muy grande y que después queda solo el sexo.68</p>
            <p>A mediados de 1996, fueron invitados por la cadena MTV para sus famosas sesiones «unplugged» (desenchufadas) en Miami. Luego de rechazar la invitación varias veces, Soda Stereo logró que la cadena aceptara su propuesta de tocar con sus instrumentos eléctricos «enchufados», pero reorquestando y modificando las versiones clásicas para hacerlas más lentas y musicalmente más complejas, agregando la voz femenina de Andrea Echeverri de Aterciopelados en una notable interpretación de «En la ciudad de la furia». Además de esta las canciones que se desarrollaron fueron: Un misil en mi placard, Entre Caníbales, Pasos, Zoom, Cuando pase el temblor, Té para tres, Ángel eléctrico, Terapia de amor intensiva, Disco Eterno, Ella usó mi cabeza como un revólver, Paseando por Roma y Génesis. Esta presentación fue registrada parcialmente en la placa Comfort y Música Para Volar (1996) y de manera completa en una nueva versión del álbum editado en 2007. El álbum incluyó además cuatro temas nuevos que habían quedado fuera de ‘‘Sueño Stereo y un track interactivo con historietas e imágenes en video de la presentación en MTV.</p>
            <p>El 30 de octubre, Soda Stereo fue la primera banda latinoamericana en realizar un concierto para ser transmitido por Internet, en el programa ¿Cuál es?, conducido por Mario Pergolini en la radio argentina Rock & Pop, desde el auditorio de la tienda de instrumentos musicales Promúsica en Buenos Aires.69</p>
            <p>Mientras se realizaba la gira del Unplugged, ocurrió un evento que dejó los ánimos de la banda en muy mal estado e hizo que entrara en su recta final. La banda estaba en un hotel de Estados Unidos descansando, cuando los hermanos Diego, Ezequiel y Pedro Fainguersch, que eran músicos invitados, realizaron una broma pesada: chorrearon con un matafuegos por debajo de la puerta del cuarto. Como respuesta, los miembros de la banda vaciaron otro matafuegos en el cuarto de los hermanos Fainguersch. El hotel sancionó económicamente a la banda por destrozos en las instalaciones, y se generó una discusión entre los miembros acerca de quién debía cargar con la multa: Zeta Bosio y Charly Alberti decían que debían ser los hermanos Fainguersch por haber iniciado la pelea, mientras que Gustavo Cerati decía que todos los miembros de la comitiva deberían pagar con un descuento porcentual en su salario. A lo largo de su carrera, la banda había tenido muchas discusiones como ésta, pero Cerati siempre se imponía. Pero esta vez un nuevo factor se le agregó a las discusiones: por primera vez hicieron una votación entre los miembros de la banda, y el resultado fue distinto.</p>
            <p>Terminamos votando Charly, Gustavo y yo; el veredicto fue que los hermanos Fainguersch debían pagar por su broma pesada y cuando Daniel Kon les hizo su liquidación retuvo el dinero correspondiente a esa factura por "destrucción". Como consecuencia de esto, los hermanos Fainguersch dejaron la banda muy enojados y Gustavo se quedó con una espina clavada: no había podido imponerse.</p>
            <p>Dos días después de aquello, el 23 de noviembre cerrábamos como acto de clausura de un festival alternativo del que había participado Nick Cave. Créase o no, el malestar que había generado la discusión sobre el incidente de los matafuegos era muy grande y el clima que intoxicaba el ambiente de la camioneta que nos llevaba a la cancha de Ferro era notablemente denso. Gustavo parecía realmente molesto y casi no hablaba. Fue uno de nuestros conciertos más deslucidos.</p>
            <p>Si alguna vez —y fueron muchas— dijimos que cuando se acabara la diversión se acababa Soda, parecía que había llegado el momento.</p>
            <p>Zeta Bosio en su libro <em>Yo conozco ese lugar</em> (2016).55</p>
            <p>La gira terminó a fines de noviembre de 1996, y tras ella los miembros volvieron a distanciarse, refugiándose cada uno en sus círculos íntimos.</p>
            <h4 id="giraRetiro">Gira de retiro (1997)</h4>
            <p>Los meses siguientes hubo un silencio con respecto al futuro de la banda. La broma pesada de los hermanos Fainguersch con los matafuegos, y la derrota de Gustavo en la votación subsiguiente, habían dañado drásticamente el clima dentro de la banda. Crecieron los rumores de una separación y tras un tiempo estos llegaron a los diarios, lo que alarmó a Zeta, quien se comunicó con Gustavo para saber si eran ciertos. Gustavo le dijo que quería terminar ahí mismo con la banda. Zeta trató de convencerlo argumentando que toda la comitiva dependía económicamente de la banda y quedaría sin trabajo si hubiera una separación, pero fue en vano. Cuando Charly se enteró, reaccionó muy negativamente: amenazó con acciones legales si la banda se separaba abruptamente, y exigió que por lo menos hicieran una gira de despedida. El mánager de la banda, Daniel Kon, se metió en el conflicto y logró convencer a Gustavo, quien terminó accediendo a regañadientes a hacer una gira de despedida, pero estableciendo sus condiciones: sería una gira corta con muy pocos recitales. Todos aceptaron.55</p>
            <p>El 1 de mayo de 1997 Soda Stereo anunció oficialmente su retiro mediante un comunicado de prensa. Al día siguiente todos los diarios se hicieron eco de la noticia y el diario Clarín dedicó un gran espacio en su portada para ello. Gustavo publicó al día siguiente en el suplemento «Sí» (juvenil) del diario Clarín lo que sería «La carta del adiós»:</p>
            <blockquote>
                <p>Estas líneas surgen de lo que he percibido estos días en la calle, en los fans que se me acercan, en la gente que me rodea, y en mi propia experiencia personal. Comparto la tristeza que genera en muchos la noticia de nuestra separación. Yo mismo estoy sumergido en ese estado porque pocas cosas han sido tan importantes en mi vida como Soda Stereo. Cualquiera sabe que es imposible llevar una banda sin cierto nivel de conflicto. Es un frágil equilibrio en la pugna de ideas que muy pocos consiguen mantener por quince años, como nosotros orgullosamente hicimos. Pero, últimamente, diferentes desentendimientos personales y musicales comenzaron a comprometer ese equilibrio. Ahí mismo se generan excusas para no enfrentarnos, excusas finalmente para un futuro grupal en que ya no creíamos como lo hacíamos en el pasado. Cortar por lo sano es, valga la redundancia, hacer valer nuestra salud mental por sobre todo y también el respeto hacia todos nuestros fans que nos siguieron por tanto tiempo. Un fuerte abrazo.</p>
            </blockquote>
            <p>La gira estaba prevista para no ser larga como las anteriores, donde pasaban por varios países del continente. Esta vez sólo tocarían en cuatro: México, Venezuela, Chile y Argentina, y harían solamente seis recitales.</p>
            <p>Durante los ensayos para la gira final, la banda dejó una participación en el disco <em>Tributo a Queen: Los Grandes del Rock en español</em> que sería lanzado en octubre de 1997, para el cual graban «Algún Día», cover en español del tema «Some day, one day» de Queen, publicada en su respectivo álbum <em>Queen II</em> en 1974. Esta sería la última grabación en estudio de la banda.</p>
            <p>El último concierto fue el 20 de septiembre de 1997 en el estadio de River Plate. Se grabó el concierto en vivo, que fue editado en dos CD separados, bajo el nombre de <em>El Último Concierto «A» y «B»</em>. Años después, en 2005, se publicó el esperado DVD del histórico concierto <em>Soda Stereo: El último concierto</em>. El recital finalizó con la épica y emocionada interpretación del tema «De música ligera». Sin aún haber acabado de tocar y extendiendo el final de la canción, un emocionado Gustavo Cerati casi hasta las lágrimas, dedicó su recordado pequeño discurso, inmortalizando este momento como uno de los más emocionantes en la historia de la música iberoamericana:</p>
            <p>No sólo no hubiéramos sido nada sin ustedes, sino con toda la gente que estuvo a nuestro alrededor desde el comienzo; algunos siguen hasta hoy. ¡Gracias totales!</p>
            <p>Acabado esto, los tres músicos muy emocionados se despidieron.</p>
            <h4 id="postSoda">Post-Soda (1997-2007)</h4>
            <p>A pesar de los constantes rumores de reunión, los cuales irónicamente comenzaron al poco tiempo de la separación, pocas noticias hubo sobre Soda, salvo un especial para TV de El último concierto producido por la cadena HBO y un documental llamado Soda Stereo: La Leyenda, producido por MTV. Finalmente en 2002 se volvió a ver al trío reunido en los premios MTV Latinoamérica para recibir el premio Legend por su trayectoria musical.</p>
            <p>A siete años de la separación era muy raro el hecho que no existiesen lanzamientos oficiales, por lo que a fines de 2003 se anunció que Sony Music lanzaría el primer DVD de Soda Stereo y que contendría mucho material inédito, proporcionado por Gustavo, Zeta y Charly, además de personas muy allegadas a la banda. Estaba claro desde un principio que la producción sería por parte de Sony y la productora Cuatro Cabezas (con Mario Pergolini al frente).</p>
            <p>El resultado salió a la calle en noviembre de 2004 y fue titulado Soda Stereo: Una parte de la Euforia (1983-1997). Un documental que resumía la historia de la banda a través de escenas de conciertos, backstage, entrevistas, ensayos, pruebas de sonido, presentaciones en TV, etc. No obstante dicho DVD sólo contenía la historia de Soda en Sony/CBS, excluyendo la etapa en BMG, correspondiente a Sueño Stereo y Comfort y Música Para Volar (de 1994 a 1996), lo que lo hacía un documento incompleto.</p>
            <p>El 20 de septiembre de 2005 se editó en Argentina un DVD sobre el concierto final que diera Soda Stereo exactamente ocho años antes en el Estadio de River Plate, con el título de <em>El Último Concierto (En Vivo)</em>. El DVD, a diferencia del especial que produjo HBO, estaba centrado en el concierto de Buenos Aires en audio 5.1 e incluía dos temas que habían quedado afuera anteriormente: «Juego de seducción» y «Sobredosis de TV». Además, incluyó una opción multi cámara para una sesión de ensayo de «Primavera 0» y un documental de 25 minutos de la gira de despedida con imágenes de los conciertos y pruebas de sonido de México, Venezuela, y Argentina. También se incluyó una entrevista al desaparecido «cuarto Soda» Alfredo Lois, autor de ese trabajo, uno de los últimos que hiciera antes de fallecer.</p>
            <h4 id="meVerásVolver">Gira Me Verás Volver (2007)</h4>
            <p>La reunificación de Soda Stereo era el tema obligado en cualquier entrevista con sus integrantes luego de la separación. Tanto que Zeta Bosio declaró una vez:</p>
            <blockquote>
                <p>¡Un día soñé que no me preguntaban más por la vuelta de Soda!</p>
            </blockquote>
            <p>En 2007, al cumplirse 10 años de su separación, la banda decidió reunirse por una vez con el fin de realizar una gran gira continental. El 6 de junio de 2007, se conoció la noticia, y el 9 se oficializó: Soda Stereo volvería a los escenarios mediante una única gira americana llamada Me Verás Volver (frase emblemática del grupo tomada de la estrofa final de la canción «En la ciudad de la furia»). La gira comenzaría el 19 de octubre en el Estadio Monumental de River Plate de la ciudad de Buenos Aires y originalmente contemplaba la realización de 2 recitales en Buenos Aires, seguidos de presentaciones en varios países americanos. Sin embargo desde el momento en que se pusieron en venta las entradas quedó en evidencia que el programa original quedaría completamente desbordado y que se estaba frente a un gigantesco acontecimiento cultural de alcance continental. Inmediatamente se programó una tercera presentación en Buenos Aires.</p>
            <p>Posteriormente se agregaron 2 fechas más en Buenos Aires, y luego se le sumó una fecha de aparente cierre para el 15 de diciembre en la Ciudad de Córdoba, aunque en la presentación de Buenos Aires del 3 de noviembre el grupo anunció el cierre de la gira previsto en esa misma ciudad para el día 21 de diciembre; por lo que finalmente se duplicaron los recitales previstos en River y se ampliaron los programados en otras partes incluyendo nuevas ciudades para programar presentaciones en Chile (2), Ecuador, Colombia, Venezuela y Panamá (1), México (4), Estados Unidos (3), Perú (2), en un total de 13 ciudades.</p>
            <p>A principios de julio, Sony-BMG lanzó un nuevo álbum llamado <em>Me Verás Volver (Hits & +)</em>, un CD con 18 reediciones de temas en estudio los cuales fueron remasterizados en 2007. El disco no contiene temas nuevos, pero incluye un código para acceder a contenidos exclusivos en su sitio web, entre ellos grabaciones de los temas ejecutados en la gira. El álbum alcanzó el primer puesto en ventas en Argentina y Chile.</p>
            <p>El 20 de septiembre, a exactamente diez años de su último concierto, Soda Stereo realizó su esperada conferencia de prensa en la discoteca Club Museum, instalada en un histórico edificio del barrio de San Telmo diseñado por Gustave Eiffel en el que años antes habían filmado el video «En la ciudad de la furia». La sorpresa fue que al comienzo ofrecieron un mini-recital de dos temas, lo que significó su vuelta formal a los escenarios. Los temas elegidos fueron «Sobredosis de TV» y «En la ciudad de la furia», que se disfrutaron en sus versiones originales. Los temas fueron interpretados solamente por ellos tres y sus instrumentos. En dicha conferencia aclararon que a partir de 2008 tienen previsto retornar a sus respectivas actividades individuales. A la pregunta de una periodista sobre cuál sería el equivalente en 2007 del «gracias totales» con que cerraron el recital de 1997, Cerati contestó:</p>
            <blockquote>
                <p>No tengo idea de qué voy a decir ahora: por ahí sea un “Olas totales”, tsunami de por medio.</p>
            </blockquote>
            <p>En octubre de 2007 Sony-BMG lanzó <em>Confort y música para volar</em> en su versión de DVD. La diferencia que tiene dicho DVD con respecto al CD editado en 1996 es que se incluye el unplugged completo.</p>
            <p>Frente a la conmoción continental que produjo la vuelta de Soda Stereo, productores de todos los orígenes, incluidos los responsables del Festival de Viña del Mar, comenzaron los contactos para contratar nuevos conciertos del grupo. En todos los casos se encontraron con una frase terminante de Gustavo Cerati:</p>
            <blockquote>
                <p>La unión es una burbuja en el tiempo.</p>
            </blockquote>
            <p>Finalmente, el 19 de octubre se produjo el esperado retorno de Soda Stereo en el Estadio de River Plate. En la oportunidad, un enorme cartel contenía una frase compuesta con títulos de sus canciones:</p>
            <blockquote>
                <p>"Cuando pase el temblor en la ciudad de la furia sonará de música ligera y estaremos prófugos detrás de la persiana americana."</p>
            </blockquote>
            <p>La banda se presentó acompañada de uno de los principales "cuartos soda" de su historia, Tweety González (teclados), así como con Leandro Fresco (teclados, percusión y coros) y Leo García (guitarra y voz). El recital duró más de tres horas y tocaron 28 temas, abriendo con la reproducción de un extracto de "Algún Día" (la canción que grabaran 10 años antes para el disco Tributo a Queen) mientras se mostraban imágenes de la historia musical de Soda Stereo, hasta la aparición de Gustavo, Zeta y Charly sobre el escenario para comenzar a tocar "Juego de seducción" y cerrando con "Nada Personal" y "Te hacen falta vitaminas", tres de sus temas más antiguos, un set-list que mantuvieron en todos los recitales de la gira.</p>
            <p>Luego de tres recitales en Buenos Aires (19, 20 y 21 de octubre), Soda se presentó en Santiago de Chile (24 y 31 de octubre), con una presentación intermedia en Guayaquil (27 de octubre) junto con Daniel Sais en el tema "Prófugos", volviendo a realizar dos conciertos más en Buenos Aires (2 y 3 de noviembre) y luego viajar a México donde actuaron en Monterrey (9 de noviembre), Zapopan (12 de noviembre), el D.F. (15 y 16 de noviembre), Los Ángeles (21 de noviembre), Bogotá (24 de noviembre), Panamá (27 de noviembre), Caracas (29 de noviembre), Miami (4 y 5 de diciembre), Lima (8 y 9 de diciembre) y Córdoba, Argentina (15 de diciembre); en todos los casos con entradas agotadas salvo en Los Ángeles. En total, el regreso de Soda Stereo habrá convocado un millón de personas.</p>
            <p>Entre los diálogos que Gustavo Cerati mantuvo en nombre de la banda con los seguidores durante los recitales se destacaron los momentos en que aquel agradeció los aplausos con un "gracias" y la gente respondió "totales!", así como cuando cantaba "Un millón de años luz" ("no vuelvas sin razón") y dijo:</p>
            <blockquote>
                <p>"Nosotros tenemos una gran razón para volver: ¡ustedes!"</p>
            </blockquote>
            <p>El 21 de diciembre de 2007 se realizó el último recital en el Estadio de River en la ciudad de Buenos Aires, incluyendo tres temas que no estuvieron en el resto de la gira: "Si no fuera por…", "Terapia de amor intensiva" y "Lo que sangra (La cúpula)". A la banda y los tres músicos invitados que realizaron la gira se agregaron Andrea Álvarez ("Pic-nic en el 4to B"), Richard Coleman ("No existes"), Fabián "Zorrito Vön" Quintiero ("Danza rota" y "Prófugos"), Carlos Alomar ("Lo que sangra (La cúpula)" y "Terapia de amor intensiva") y Gillespi ("Signos" y "Fue"). Cerati volvió a pronunciar su famosa expresión, "gracias totales", luego de tocar el tema "De música ligera" y rompió la guitarra al terminar el solo final en "Sueles dejarme solo".</p>
            <p>Los críticos han sido coincidentes en destacar el alto nivel de ensayos y el buen ensamble de la banda, así como un ambiente de entendimiento entre los músicos, algo que también destacó Gustavo Cerati desde el escenario, a la vez que se ha despedido con un "hasta dentro de diez años".</p>
            <p>En agosto de 2008 el sello Sony BMG lanzó a la venta el DVD de la gira "Me Verás Volver", que contiene los temas interpretados por la banda en los conciertos además de los testimonios de Gustavo Cerati, Charly Alberti y Zeta Bosio y de los invitados especiales. Además, el 18 de julio de 2008 se lanzó un CD doble con las mismas canciones, y se comercializó por separado.</p>
            <h4 id="muerteGustavo">Muerte de Gustavo Cerati y Sép7imo Día (2008-2020)</h4>
            <p>En marzo de 2010, Zeta Bosio dijo en una entrevista que Soda Stereo tenía planeado regresar a los escenarios con un nuevo álbum de estudio. Sin embargo, el 16 de mayo, Cerati sufrió un ACV del que no logró recuperarse. Luego de cuatro años de permanecer en coma, falleció el 4 de septiembre de 2014.</p>
            <p>En 2015, Cirque du Soleil anunció un espectáculo temático en homenaje a la banda titulado Sép7imo Día - No descansaré, presentándolo entre 2017 y 2018. Zeta y Charly volvieron a reunirse para producir la banda sonora, remezclando pistas originales de diferentes canciones. En marzo de 2017 fue publicado el álbum de rémixes SÉP7IMO DÍA, que incluye los 18 tracks ejecutados en el evento. A raíz de esto, empezaron a considerar la idea de volver a tocar juntos.</p>
            <h4 id="graciasTotales">Gracias Totales (2020-2022)</h4>
            <p>En octubre de 2019, los miembros restantes de Soda Stereo anunciaron la gira Gracias Totales a través de un vídeo y una carta a sus seguidores en sus redes sociales. Comenzó el 29 de febrero de 2020 en el Estadio El Campín de Bogotá, Colombia. Tienen programado visitar Argentina, Perú, Chile, México, Paraguay, Estados Unidos, entre otros países de América durante la gira. Debido a la pandemia de COVID-19, todos los conciertos restantes de la gira tuvieron que ser reprogramados para 2021 y 2022.</p>
            <p>En la gira, Bosio y Alberti fueron acompañados por diversos cantantes tanto en vivo como a través de videos pregrabados, entre los que se menciona a Richard Coleman, Zorrito von Quintiero, Chris Martin, Adrián Dárgelos, Rubén Albarrán, Álvaro Henríquez, Mon Laferte, Juanes, Simón Bosio (hijo de Zeta), Benito Cerati (hijo de Gustavo), Julieta Venegas, Catupecu Machu, Gustavo Santaolalla, entre otros, además de proyectarse videos de Cerati.</p>
            <p>El 23 de junio de 2021 presentaron su primer video animado de la canción «¿Por qué no puedo ser del Jet-Set?» en su canal oficial de YouTube. Durante ese año y principios de 2022, estrenaron los videos animados de las canciones «Sobredosis de TV», «Imágenes Retro», «Danza rota», «Prófugos», «En camino», «El ritmo de tus ojos», «Lo que sangra (La cúpula)», «Un millón de años luz», «Entre caníbales», «Luna roja», «Toma la ruta», «Crema de estrellas» y «Paseando por Roma».</p>
            <p>El 7 y 8 de noviembre de 2022, Zeta Bosio y Charly Alberti fueron invitados por Coldplay en el Estadio Monumental para interpretar «Persiana Americana», «De Música Ligera» y «Yellow» del grupo británico, en la gira Music of the Spheres World Tour.</p>
            <br />
            {// eslint-disable-next-line
                <p>Fuente: <a target="_blank" href="https://es.wikipedia.org/wiki/Wikipedia:Portada"><em>Wikipedia</em></a></p>
            }
        </>
    );
}
export { BioSoda };